### ISSUE TITLE
Project screen - Kanban view: Total is incorrect

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1016]

**Comment by LAlexMHllc** [comment]
Closing, because this is confusing. Will test more.

**Comment by LAlexMHllc** [comment]
Screenshot Example

![kanban_view_total_is_incorrect](https://user-images.githubusercontent.com/11938477/100149680-90771100-2e6c-11eb-9640-5839bf03ecf3.png)

**Comment by LAlexMHllc** [comment]
NOTE: Just found out that the "Total" includes tasks that do not have a Stage selected (not required). So what the user sees for Total might not match the number of tasks/issues on the Kanban.

**Comment by bluenevus** [comment]
So now I'm confused on what you are asking.  put in a new clean ticket as this is confusing
