### ISSUE TITLE
Project screen - Team view: "EXPORT TO PDF" background should be white with black text when not on focus (not mouseover). Change text on both buttons to upper/lowercase like the others.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1020]
Screenshot Example

![project_team_view_pdf_white_not_mouseover](https://user-images.githubusercontent.com/11938477/100243049-76d4d880-2f03-11eb-9e0c-e7dca39f0130.png)

**Comment by bluenevus** [comment]
consistency is key...pick one way of doing it and do it that way across the application.

**Comment by LAlexMHllc** [comment]
Also change text for both buttons to upper/lowercase like the others.

Screenshot Example

![export_btns_default](https://user-images.githubusercontent.com/11938477/100250304-82c49880-2f0b-11eb-8b1a-2036a862311e.png)

**Comment by juan-rivera-2020** [comment]
Fixed.  Pushing up in next commit.
