### ISSUE TITLE
Filter View: The modal should not close when a "Project Completion Date" is selected.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1023]
Screenshot Example

![filter_view_selected_project_completion_date_and_modal_closed](https://user-images.githubusercontent.com/11938477/100271451-7f3f0a80-2f27-11eb-8738-98d30cebb63b.png)

**Comment by bluenevus** [comment]
walk us through the steps to get to this issue because I don't know how we got here and if its everywhere or a specific screen

**Comment by LAlexMHllc** [comment]
Click Filter View tab open on any view, then click "Project Completion Date". When a date is selected on either calendar, the Filter View modal closes.

**Comment by bluenevus** [comment]
are you saying you cannot enter a date range because it closes?

**Comment by LAlexMHllc** [comment]
No. The issue is that the Filter View modal should not close just because a Project Completion Date was clicked. The modal stays open when the other form elements are selected.

**Comment by LAlexMHllc** [comment]
See related Issues #1170 and #1179

**Comment by LAlexMHllc** [comment]
Closing, since now included with Issue #1170
