### ISSUE TITLE
Project screen - Kanban view: Task percentage complete increased above Task Stage Percentage. User still has to select Task Stage.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1029]
User checked more checklist items as done for task with Task Stage=In Progress. The percentage done automatically increased above the Percentage for Task Stage "In Review". The user still needs to select Task Stage="In Review" because it did not update automatically.

Screenshot Example

![kanban_view_stage_aumatic_due_to_percentage_or_still_user_select_stage](https://user-images.githubusercontent.com/11938477/100462941-0a8bdd80-3099-11eb-828e-532af6ba9837.png)

**Comment by bluenevus** [comment]
if the users uses kanban on this, automatic stages are removed because it assumes kanban is how it works else the two would fight against each other.  its one or the other, not both because the 2 percentages won't be the same number as checklist is much more accurate while stages are general.

**Comment by bluenevus** [comment]
but we do need to think it through to harmonize it so that its more logical based on user behavior.  I don't want to make changes until we get that feedback on how they want it to behave
