### ISSUE TITLE
admin/task_stages and admin/issue_stages - tables: User created a stage with Percentage < 100, the Kanban displayed the newly created stage as last column.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1033]
Screenshot Example

![kanban_not_display_by_percentage_asc](https://user-images.githubusercontent.com/11938477/100469656-ac64f780-30a4-11eb-8791-075634235a4e.png)

Should the Percentage column be selected ASC sort by default, so the Kanban columns will display accordingly? 
Screenshot Example

![admin_stage_percentage_asc_sort](https://user-images.githubusercontent.com/11938477/100470068-7c6a2400-30a5-11eb-9368-bd960b12325a.png)

Or update Kanban column display function?

**Comment by bluenevus** [comment]
the kanban stage is supposed to be configured so that it displays in a certain order see this issue that addresses this among all enumerations #350
