### ISSUE TITLE
Project screen - On Watch tab - Timeline: Clicking an overdue task or an overdue issue should change the background color to yellow like not overdue.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1036]
Screenshot Example

![on_watch_timeline_background_overdue_should_be_yellow_onclick](https://user-images.githubusercontent.com/11938477/100479586-a24ef300-30bc-11eb-8796-c236cdc5fe0a.png)

**Comment by bluenevus** [comment]
this is being redone so hold for now

**Comment by bluenevus** [comment]
see dashboard
