### ISSUE TITLE
Change overview landing tab to tasks in sheets, maps, facility manager and have facility groups function like facility in view and ability to enter data

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1037]
Currently when a facility group is loaded it shows this screen

![image](https://user-images.githubusercontent.com/3675043/100480999-de845280-30c0-11eb-8be3-5a025dfa076b.png)

The problem is 2 fold.  first it forces the system to do a calculation which is slow and not always needed, second the place the user will likely want to engage first are the tasks.  Therefore, the facility group should load facility group level tasks as default.  This means rather than showing the image above and landing on overview, it will show the tasks in the facility group like this below so you know what facility the task is for in sheets, maps and facility manager.  

when clicking a facility group, you would have the same tabs as facility like so

![image](https://user-images.githubusercontent.com/3675043/100481603-92d2a880-30c2-11eb-96b3-2723e34eba34.png)

This also means they can manage the facility group like they do a specific facility.  The problem will be adding a task.  The user will need to select what facility the task should be assigned to in the task, issue, note risk form.

![image](https://user-images.githubusercontent.com/3675043/100481086-1f7c6700-30c1-11eb-833f-722bd2ae8985.png)

this way it only calculates the math on the overview when that tab is clicked.  Else, the landing will be on the task view and the facility group will now behave just like the facility in tasks, issues, risks notes etc

What is important is load only the data that is needed when needed.   Even though there could be a long list of tasks, you only load what fits on the page.   In facility manager and maps when they scroll down then it should load more data.  For example you can have 30k emails in your inbox, it doesn't load all of them.  It only loads what you see on the screen and as you scroll down for more, it loads in more.  Similarly as you paginate, it loads more. So in sheets, only when you click next page, should it load the next set of data.  This will be sure the user doesn't wait a long time for the page to load but spreads that out as the data is called.
 
this is related to #710

**Comment by bluenevus** [comment]
this may in part help resolve #815

**Comment by bluenevus** [comment]
in production with plenty of data...it takes about 6-7 seconds to load.  So I think the best way is to default the landing to non calculating screen ie task and have the calculations run in the background so when they switch to the overview tab it will already be there unless you have a better idea to speed up the page load

**Comment by LAlexMHllc** [comment]
Closing this issue since Tasks is default tab for Sheet and Map, until user changes their Preferences. Also, select project is being removed from forms.
