### ISSUE TITLE
Project screen - Filter View: When On Watch view is displayed, "On Watch Tasks" and "On Watch Issues" should be selected for "On Watch Filter".

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1055]
Screenshot Example

![filter_view_both_on_watch_filters_should_be_selected_on_watch_view](https://user-images.githubusercontent.com/11938477/100755537-49cc6e00-33ba-11eb-990a-c4813fe0f890.png)

**Comment by bluenevus** [comment]
well it should be one checkbox.  same why my actions...one checkbox   I think I have a ticket for this.  double check
