### ISSUE TITLE
Project screen - Filter View - "My Tasks" and "My Issues" were selected for "My-actions Filter", but it did not filter On Watch view correctly.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1056]
Screenshot Example

![filter_view_my_tasks_and_my_issues_filters_should_filter_on_watch_view](https://user-images.githubusercontent.com/11938477/100757038-e2afb900-33bb-11eb-83af-4cd3ebb66581.png)

**Comment by bluenevus** [comment]
one checkbox new requirement for one checkbox not separate ones
