### ISSUE TITLE
Project screen - Task form and Issue form - Checklists section: Include checkbox with text "My Checklists".

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1057]
When "My Tasks" or "My Issues" is checked on the Facility Summary, or selected on Filter View - My-actions Filter, then "My Checklists" will be checked by default. When a user unchecks "My Checklists", then all checklists items will display.

Screenshot Example

![task_form_issue_form_checklists_my_checklists_checkbox](https://user-images.githubusercontent.com/11938477/100761692-2bb63c00-33c1-11eb-97a1-e312541cb018.png)

**Comment by bluenevus** [comment]
well like I said in a number of places.  one checkbox for my actions and it filters everything not a bunch of separate ones
