### ISSUE TITLE
Project screen - Facility that did not satisfy filter with "My Tasks" and "On Watch Tasks" both checked displayed on the left sidebar. Facility Summary displayed with None found message, even with status=all selected.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1067]
"My Tasks" and "On Watch Tasks" were selected on Filter View first, then facility was selected on the left sidebar.

Screenshot Example

![filter_view_my_tasks_on_watch_tasks_selected](https://user-images.githubusercontent.com/11938477/100912697-d05a7b80-349e-11eb-9269-8332dbf503f2.png)

Even with "all" selected, no tasks found.
Screenshot Example

![facility_manager_view_facility_displayed_left_sidebar_yet_did_not_satisfy_filter](https://user-images.githubusercontent.com/11938477/100910360-def36380-349b-11eb-8600-b2e84da86d91.png)

**Comment by LAlexMHllc** [comment]
NOTE: "My Tasks" and "On Watch Tasks" were selected on Filter View, then facility was selected.

**Comment by bluenevus** [comment]
and you are sure you have a task with BOTH you assigned and on watch because its an AND statement not an OR

**Comment by LAlexMHllc** [comment]
The facility should not have a link on the left sidebar, because it does not satisfy the filter.

**Comment by LAlexMHllc** [comment]
Screenshot of the facility above with only "My Tasks" checked on the left, and only "On Watch" checked on the right.

![facility_manager_fairbanks_my_tasks_only_then_on_watch_task_only](https://user-images.githubusercontent.com/11938477/100919176-73af8e80-34a7-11eb-897a-fba085548387.png)

**Comment by bluenevus** [comment]
the facility should remain on the sidebar.  removing it is confusing
