### ISSUE TITLE
The function need to be consistent across the Views when a Project Summary is displayed without My Assignments, then "My Assignments" is selected; or when My Assignments is selected on ADVANCED FILTERS. 

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1068]
Screenshot Example of Map View

![map_view_facility_summary_my_task_unchecked](https://user-images.githubusercontent.com/11938477/100917565-4cf05880-34a5-11eb-928a-4632d8f77783.png)

![map_view_facility_summary_my_tasks_checked_none_found](https://user-images.githubusercontent.com/11938477/100917584-54affd00-34a5-11eb-8920-427825f8a51f.png)

Screenshot Example of Facility Manager View

![facility_manager_view_facility_summary_my_tasks_unchecked](https://user-images.githubusercontent.com/11938477/100917367-0dc20780-34a5-11eb-932f-a92b207fb8e6.png)

![facility_manager_view_my_tasks_checked_on_facility_summary_without_my_task_project_summary_displays](https://user-images.githubusercontent.com/11938477/100917413-203c4100-34a5-11eb-9c0b-f507764abbff.png)

**Comment by bluenevus** [comment]
working as designed

**Comment by bluenevus** [comment]
The requirement is if the facility doesn't fit the criteria, then it shouldn't show in the filter handle or pushpin.  the purpose of a filter is to filter out the noise not to keep it there.  In testing you may have only one or two facilities but in deployment there are hundreds and potentially thousands for others so you don't want to see that much noise thus...a filter which filters out noise that does not meet the criteria.

**Comment by LAlexMHllc** [comment]
NOTE: My ... was changed to My Actions, and will be changed to My Assignments

**Comment by LAlexMHllc** [comment]
See related Issue #1066
