### ISSUE TITLE
Project screen - Facility that did not satisfy filter with "My Issues" and "On Watch Issues" both checked displayed on the left sidebar. Facility Summary displayed with None found message, even with status=all selected.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1069]
"My Issues" and "On Watch Issues" were selected on Filter View first, then facility was selected on the left sidebar.

Screenshot Example

![filter_view_my_issues_on_watch_issues_selected](https://user-images.githubusercontent.com/11938477/100920962-df92f680-34a9-11eb-856d-77e357bb14a5.png)

Even with "all" selected, no issues found.
Screenshot Example

![facility_not_satisfy_filter_my_issues_on_watch_displays_none_found](https://user-images.githubusercontent.com/11938477/100921046-03eed300-34aa-11eb-8262-586060dc24d4.png)

**Comment by LAlexMHllc** [comment]
Screenshot of the facility above with only "My Issues" checked on the left, and only "On Watch" checked on the right.
NOTE: The issues seen in both are different.

![facility_manager_juneau_my_issues_only_then_on_watch_issues_only](https://user-images.githubusercontent.com/11938477/100921555-ba52b800-34aa-11eb-8b80-d425665e07bb.png)

**Comment by bluenevus** [comment]
its an and statement.  look here  my issue and on watch both are checked and you can see on watch and the task I'm assigned.  its an AND statement not an OR statement.  I don't understand your issue

![image](https://user-images.githubusercontent.com/3675043/100921934-3816c380-34ab-11eb-8a0f-0d70ade5f2aa.png)
