### ISSUE TITLE
If a facility that does not satsify a filter is to remain on the left sidebar for Facility Manager, Sheets, and Kanban views, the facility pushpins should remain on the map for Map view. (Consistency for select a facility and facility presently viewed.)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1070]

**Comment by bluenevus** [comment]
well the purpose of the filter is to filter out stuff you don't want to see.  It would be overwhelming to filter stuff then see a thousand facilities on the pushpin or the left handle for that matter.  The requirement is to filter out facilities where the condition doesn't apply
