### ISSUE TITLE
Project screen - Team view: Organization column does not sort

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1074]
Screenshot Example

![team_organization_column_not_sort](https://user-images.githubusercontent.com/11938477/101046802-4e765b00-354f-11eb-81c7-108300240ae4.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/101085540-91e7be00-357d-11eb-8b65-4105355bea78.png)

**Comment by bluenevus** [comment]
teams list should be 25 per page.  I'm sure later we will make the content per page configurable but for now...this is what is really needed
