### ISSUE TITLE
Project dashboard: "user: nginx AVOID..." Message displays at the bottom of the screen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1086]
Screenshot Example

![message_bottom_project_dashboard](https://user-images.githubusercontent.com/11938477/101176569-a88d2400-3614-11eb-8509-9a7e8974e07b.png)

**Comment by bluenevus** [comment]
I don't see this

[cid:6399f26f-b96a-4769-b028-3cc02f07ce68]
Frank Tucker​
Chief Executive Officer ,       Executive Office
t: 855‑294‑3547
m: 571-327-1211<tel:571-327-1211>
frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>  |      www.microhealthllc.com<https://www.microhealthllc.com/>
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
[Twitter]<https://twitter.com/microhealthllc?lang=en>
[Facebook]<https://www.facebook.com/microhealthllc/>
[YouTube]<https://www.youtube.com/user/microhealthtube>
[LinkedIn]<https://www.linkedin.com/company/microhealth-llc>
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

________________________________

**Comment by bluenevus** [comment]
strangely, its in dev only and not prod

**Comment by LAlexMHllc** [comment]
No longer displays
