### ISSUE TITLE
Facility Summary - Edit Task and Edit Issue forms: Whether or not On Watch was checked/unchecked still determines the status of the task/issue.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1089]
Facility Summary - Edit Task and Edit Issue forms: When "Close" is clicked instead of "Save", whether or not On Watch was checked/unchecked still determines the status of the task/issue.
Screenshot Example 1

![on_watch_checked_close_clicked_still_on_watch](https://user-images.githubusercontent.com/11938477/101207014-f9654280-363d-11eb-89bf-0a55ea0d8292.png)

Screenshot Example 2

![on_watch_unchecked_confirmed_close_clicked_not_on_watch](https://user-images.githubusercontent.com/11938477/101207079-14d04d80-363e-11eb-86b0-63c2da3347a5.png)

**Comment by LAlexMHllc** [comment]
NOTE: If this is the intended function, then close this issue.

**Comment by microhealthamand** [comment]
Regarding this issue, When we are check/uncheck on-watch checkbox, it is updating that record in database. Do we want to remove that functionality and save data only on Save button click?

**Comment by bluenevus** [comment]
there is a ticket for this already to perform form validation and warning that if the user changes then provide warning vs just the checkbox
