### ISSUE TITLE
Team page: PDF exports are printing with unwanted Bootstrap text in headers.  

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1103]
A few features were added to the Team table that will likely enhance the user experience (such as an all categories search filter and items per page filter).  In doing so, the Bootstrap-Vue library used for the table introduced unwanted text in all the headers.  Will fix asap.  
![image](https://user-images.githubusercontent.com/72885316/101412957-72200500-38b1-11eb-8df6-34c0b0c32c4c.png)

**Comment by bluenevus** [comment]
seems to work
