### ISSUE TITLE
task category missing on issue sheets

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1109]
![image](https://user-images.githubusercontent.com/3675043/101496258-8c9cc180-3937-11eb-9a77-629d1b514332.png)

**Comment by juan-rivera-2020** [comment]
Task Category menu added to Issues Sheets.  Please advise on current menu arrangement.  There were many different layout options for the second row of menus.  I can place both menus to the left of the red line or I can align them in the center of row, justify-right or leave as is.  
![image](https://user-images.githubusercontent.com/72885316/101559299-d5339980-398e-11eb-9836-8521493b41a6.png)
