### ISSUE TITLE
for consistency, the sheets task and issues should have the same ability to set the number of lines per page

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1112]
![image](https://user-images.githubusercontent.com/3675043/101496940-5f9cde80-3938-11eb-91ca-24147b7531e1.png)

we either stick with the box with the count above

or like on other pages here 

![image](https://user-images.githubusercontent.com/3675043/101496990-73e0db80-3938-11eb-8f16-625ccb205fc3.png)

NOT two different styles.  consistency is key

**Comment by LAlexMHllc** [comment]
Not able to set number of lines per page
