### ISSUE TITLE
sheets and team does not use the same grid or pagination styles

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1113]
we need to use one style or the other not both

the grid style on the team page is like so 
![image](https://user-images.githubusercontent.com/3675043/101497108-9c68d580-3938-11eb-9f57-7f5107abed3f.png)

with pagination like so 
![image](https://user-images.githubusercontent.com/3675043/101497139-a38fe380-3938-11eb-9503-f944e4917320.png)

while sheets is like so 
![image](https://user-images.githubusercontent.com/3675043/101497166-ad194b80-3938-11eb-9c2a-02eab2ac9b50.png)

and pagination like so
![image](https://user-images.githubusercontent.com/3675043/101497212-ba363a80-3938-11eb-9f38-8975d5c9923d.png)

pick one style and stick to it on all controls

**Comment by juan-rivera-2020** [comment]
If the new Team data table passes Testing, I will use the same table library in Sheets.  This should also address issue #1112.

**Comment by LAlexMHllc** [comment]
Pagination styles still differ.
Screenshot Example

![team_vs_manage_pagination](https://user-images.githubusercontent.com/11938477/106296865-2ee27280-6220-11eb-97ca-a210501924eb.png)

**Comment by LAlexMHllc** [comment]
Sort order not indicated on table headers on Manage view, as it is on Team view.
Screenshot Example

![manage_table_headers_sort_order_not_indicated](https://user-images.githubusercontent.com/11938477/106492507-fba11d00-6485-11eb-80d5-31468c0712b0.png)
