### ISSUE TITLE
Project screen - Facility Summary - Issues: Task Category not saving on Add/Edit forms.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1117]
Project screen - Facility Summary - Issues: User selected Task Category, clicked Save. User filtered by Task Category, and No issues found. User edit same issue, and previously selected Task Category was not selected (did not stick).
Screenshot Example

![facility_summary_issues_selected_task_category_clicked_save_filtered_not_found](https://user-images.githubusercontent.com/11938477/101499914-d091c580-393b-11eb-918b-384a9a582048.png)

![facility_summary_issues_selected_task_category_clicked_save_filtered_not_found_2](https://user-images.githubusercontent.com/11938477/101499942-d8516a00-393b-11eb-93ca-173b054dbbe1.png)

**Comment by microhealthamand** [comment]
This issue seems fixed in PR https://github.com/MicroHealthLLC/mGis/pull/1144 which is about issue #964
