### ISSUE TITLE
Project screen - On Watch view - Filter View for "Search by Issue Users": Results displayed due to Related Issue assigned user for issue that was not on watch.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1125]
On Watch view: User selected Frank for "Search by Issue Users". Results updated to display an issue for another user (Curtis) that was assigned the issue without checklist assigned users. Results found were due to Related Issue - Assigned User matching filtered user Frank.
Screenshot Example

![on_watch_filtered_by_issue_users__results_for_related_issue_not_on_watch](https://user-images.githubusercontent.com/11938477/101534767-a81ec100-3965-11eb-8240-2835d367ba34.png)

Screenshot of Edit Issue for Related Issue that was found using the filter above

![on_watch_filtered_by_issue_users__results_for_related_issue_not_on_watch_2](https://user-images.githubusercontent.com/11938477/101535628-ed8fbe00-3966-11eb-93e7-667dc35cce36.png)

**Comment by bluenevus** [comment]
I don't want to do any more work in On Watch view because its going away
