### ISSUE TITLE
per project enumerations is missing task stages and issue stages

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1130]
![image](https://user-images.githubusercontent.com/3675043/101639481-5de91e80-39fd-11eb-9eb7-82c7084f8984.png)

**Comment by LAlexMHllc** [comment]
See related issue #1131

**Comment by LAlexMHllc** [comment]
See related Issue #1137

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102414150-041bc200-3fc4-11eb-8496-f0b9531db04c.png)

**Comment by LAlexMHllc** [comment]
Looks good. Just change "Task Stage" to "Task Stages" and "Issue Stage" to "Issue Stages"
