### ISSUE TITLE
Filter View - Search by Task/Issue Users missing users. List is empty for both.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1153]
Screenshot Example

![filter_view_search_by_user_missing_users](https://user-images.githubusercontent.com/11938477/101918296-34fc9100-3b97-11eb-9d5c-075b6e6f8b8e.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102254640-e4f33680-3ed6-11eb-991e-5f4cfc2677d4.png)

**Comment by LAlexMHllc** [comment]
"Super Admin" displays as an option.

**Comment by LAlexMHllc** [comment]
Closing this issue for this release. "Super Admin" included with Issue #1184
