### ISSUE TITLE
there should be only ONE progress range and it covers tasks, issues, and risks.

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1162]
![image](https://user-images.githubusercontent.com/3675043/101989692-436aab80-3c70-11eb-9f48-f2ea07afe5e3.png)

its way to complicated to separate them as users.  there should be only one field that handles both and in the future, risks etc

**Comment by LAlexMHllc** [comment]
NOTE: See related Issues #1134, #1135, and #1136

**Comment by bluenevus** [comment]
should go to the combined section 
![image](https://user-images.githubusercontent.com/3675043/103051823-af4cee00-4565-11eb-9a98-a59fa40026af.png)

**Comment by LAlexMHllc** [comment]
Should include "Risks" in label text and filter function.
