### ISSUE TITLE
there should be only one box to search by users not one for issues and tasks

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1163]
![image](https://user-images.githubusercontent.com/3675043/101989744-8cbafb00-3c70-11eb-953b-9e8c0f4bdd19.png)

its way to complicated to separate them as users. there should be only one field that handles both and in the future, risks etc

**Comment by bluenevus** [comment]
should go to the combined section

![image](https://user-images.githubusercontent.com/3675043/103051802-a78d4980-4565-11eb-8df7-f9142bd8c04b.png)

**Comment by LAlexMHllc** [comment]
Be sure to include risk users in "Search by Users" filter
