### ISSUE TITLE
Filter View - My Assignments and On Watch selected; Facility that did not satisfy filter displayed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1174]
User selected "My Issues" and "On Watch Issues" on Filter View, 1 Facility displayed on Project Summary.
Screenshot Example

![filter_view_my_issues_on_watch_issues_1_facility](https://user-images.githubusercontent.com/11938477/102128068-52da2800-3e1b-11eb-95c0-d8b702d6410b.png)

User clicked the Facility, and "No issues found" displayed under the Issues tab.
Screenshot Example

![filter_view_my_issues_on_watch_issues_facility_selected_no_issues_found](https://user-images.githubusercontent.com/11938477/102128186-7dc47c00-3e1b-11eb-8b92-656da942caec.png)

**Comment by LAlexMHllc** [comment]
NOTE: My Issues are now included in My Actions, which will be changed to My Assignments

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/103419087-86c58500-4b5f-11eb-8745-c7824e79c12f.png)

![image](https://user-images.githubusercontent.com/74916983/103419097-9218b080-4b5f-11eb-9c50-b0d3ef5632ac.png)

**Comment by LAlexMHllc** [comment]
Closing this issue since My Assignments includes My Tasks and My Issues, so this will be fixed with Issue #1173.
