### ISSUE TITLE
overview issue calculations need to include "Associated Task Categories" 

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1192]
![image](https://user-images.githubusercontent.com/3675043/102295878-44266a80-3f1a-11eb-9a59-36de61a7c79b.png)

This will allow the users to see the associated task category numbers so we know how many issues are associated with what task category and its level of completion

**Comment by LAlexMHllc** [comment]
See related Issue #1208

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/106031919-d3887700-609d-11eb-9f83-4c80cb33c1c3.png)
