### ISSUE TITLE
Facility Summary - Overview - Issues section: Stats did not update according to Filter by Task Category

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1208]
Screenshot Example

![facility_summary_overview_issues_stats_not_update_according_task_category](https://user-images.githubusercontent.com/11938477/102511654-09761c80-4057-11eb-846a-db2192fc2c3a.png)

**Comment by LAlexMHllc** [comment]
See related Issue #1192

**Comment by microhealthamand** [comment]
@LAlexMHllc  The list is different because of the status filter in Task and Issue tab. If you change it to all instead of active it will show all result. The overview tab shows all result when task category is applied i.e. issues which are complemented and issues which are active.

**Comment by LAlexMHllc** [comment]
Selected "all" for status, and stats still did not update on Issues section.
Screenshot Example

![facility_summary_overview_issues_stats_not_update_according_task_category_2](https://user-images.githubusercontent.com/11938477/103104097-56c43200-45f3-11eb-8c9d-6c8552329059.png)
