### ISSUE TITLE
Provide the ability to filter to a particular task categories on the Overview page

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mGis#1215]
This would be the same functionality as selecting a different Filter by Task Category on the Filter View. The user just wants to be able to do on the Overview page and not have to do it on the Filter View

**Comment by LAlexMHllc** [comment]
For Facility Manager, Sheets, and Map views

**Comment by microhealthamand** [comment]
Facility manager
![image](https://user-images.githubusercontent.com/74916983/102936669-91549000-4476-11eb-8162-4481287955d8.png)

Sheet view
![image](https://user-images.githubusercontent.com/74916983/102936714-a5988d00-4476-11eb-8f11-c578c30eda86.png)

**Comment by LAlexMHllc** [comment]
Closing issue; see Issue #1258
