### ISSUE TITLE
Facility Manager:  Make Notes UI and functionality consistent w/Task and Issues

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1225]

**Comment by juan-rivera-2020** [comment]
Asterisk added in placeholders of required fields and appropriate message added below form (for Task and Issue forms).
![image](https://user-images.githubusercontent.com/72885316/102661518-f9d80000-414a-11eb-8eff-53dea558f941.png)

**Comment by LAlexMHllc** [comment]
Remove "Delete" from Add Note
Screenshot Example

![remove_delete_from_add_note](https://user-images.githubusercontent.com/11938477/102904202-68fd6f00-443f-11eb-9eaa-d6733d71087b.png)

**Comment by bluenevus** [comment]
leave it for now...not worth addressing for the near or mid term future

**Comment by bluenevus** [comment]
this feature is changing into discussions
