### ISSUE TITLE
my tasks /  issues and complete vs active and on watch should be inclusive on this list consolidating multiple filters into one multiselect dropdown

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1227]
This drop down here

![image](https://user-images.githubusercontent.com/3675043/102661948-d2cdfe00-414b-11eb-9546-c5265d12bf1c.png)

should behave like these dropdownlists in the system where you can select multiple critera

![image](https://user-images.githubusercontent.com/3675043/102661915-bfbb2e00-414b-11eb-8ab4-275aec2318e1.png)

This will consolidate

Overdue
On Schedule
On Watch
My Tasks

This way the user can select one or multiple or clear all to see all.  this simplifies the number of ways users select options and puts them all into a single drop down that can do multiple things for the same purpose

**Comment by bluenevus** [comment]
active task and completed should be on this list

active should be default

![image](https://user-images.githubusercontent.com/3675043/102662170-4243ed80-414c-11eb-8ec0-4a8c94d8867a.png)

**Comment by bluenevus** [comment]
this same filter should replace the multiple same filters in the left advanced filter handle

**Comment by juan-rivera-2020** [comment]
Frank, label or name for this filter?  Some options:  

- Additional Filters
- Advanced Filters
- Misc Filters
- Advanced Search
- 
Will any of these work or did you have one in mind?

**Comment by bluenevus** [comment]
looks like you have it in the filter handle we now need to do the same in task and issues combining the multiple into the same one multiselect dropdown like you did here

![image](https://user-images.githubusercontent.com/3675043/103058519-63ec0d00-4570-11eb-8ec3-b172baf7fdb5.png)

and the "advanced filter" name in the image above should be called "Flags" remember there is a requirement that uses these flags

**Comment by microhealthamand** [comment]
Related #1278

**Comment by LAlexMHllc** [comment]
1. Option text should be in uppercase and lowercase as follows:
Active
Completed
Overdue
On Schedule
My Actions
Not My Actions
On Watch
Not On Watch

2. Active should be selected by default

3. The filter may be empty to be all inclusive, so need placeholder text.

4. Please fix all filtering issues
