### ISSUE TITLE
Remove admin/risk_milestones link and screen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1233]
Screenshot Example

![remove_risk_milestones_link_screen](https://user-images.githubusercontent.com/11938477/102791486-135c9000-4375-11eb-9062-4cd81b05e9ab.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102798748-84a14080-437f-11eb-8ce2-9f4c8b83c32a.png)
