### ISSUE TITLE
Increase width of checklist item name, and move Due Date on same line as Assigned To

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1240]
Screenshot Example

![increase_width_checklist_item_name](https://user-images.githubusercontent.com/11938477/102812970-04d2a080-4396-11eb-9bd0-66f3e164c177.png)

**Comment by LAlexMHllc** [comment]
Maybe move Due Date to same line as Assigned To

**Comment by bluenevus** [comment]
agree

**Comment by LAlexMHllc** [comment]
Decrease the space on the bottom of Task checklist item to be like Issue checklist item.
Screenshot Example

![checklist_item_remove_space_bottom_task_to_be_like_issue](https://user-images.githubusercontent.com/11938477/102903368-3e5ee680-443e-11eb-81c5-671db11304cc.png)

**Comment by bluenevus** [comment]
yes
