### ISSUE TITLE
Risk - Include required field "Name"; change "Risk Milestone" to "Task Category"; add "Risk Stage".

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1241]
Client Panel - New and Edit forms; and Risks List
Screenshot Example

![client_panel_risk_form](https://user-images.githubusercontent.com/11938477/103230232-ec690580-4902-11eb-811b-0284841b32cd.png)

Admin Panel - New and Edit forms, Filter, and Table
Screenshot Example

![admin_risks_change_risk_milestones_to_task_categories_include_name](https://user-images.githubusercontent.com/11938477/103230480-934da180-4903-11eb-8faa-36087d5e9670.png)

**Comment by bluenevus** [comment]
its the existing task category enumeration not a new one

**Comment by LAlexMHllc** [comment]
Include "Name", "Risk Stage" on forms, filter, and table.
