### ISSUE TITLE
Facility Tasks percentage complete did not update Facility Group percentage.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#125]
Screenshot Example

![percentage_facility_tasks_complete_not_update_facility_group_percentage](https://user-images.githubusercontent.com/11938477/78261010-a9d9e000-74cc-11ea-961b-ded248d95369.jpg)

**Comment by bluenevus** [comment]
Did it require a screen refresh?

**Comment by LAlexMHllc** [comment]
yes
