### ISSUE TITLE
admin/projects - Advanced tab: Enumerations changes

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1250]
1. Change text to "Task Stages in Project"
2. Move both stages to their group
3. Do not include users and facilities with state=inactive for New Project

Screenshot Example

![admin_project_advanced_enumerations](https://user-images.githubusercontent.com/11938477/102930518-94498380-446a-11eb-9162-de5afe28d242.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102937994-615abc00-4479-11eb-8be6-af75cac340bc.png)
