### ISSUE TITLE
Facility changed status to Complete, but Facilities Group status did not update.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#126]
Screenshot Example

![facility_status_did_not_update_facility_group_status](https://user-images.githubusercontent.com/11938477/78261759-a2ff9d00-74cd-11ea-8b52-0b1e68e70215.jpg)

**Comment by bluenevus** [comment]
I think it requires a screen refresh but like the other, we would want it updated without the refresh

**Comment by LAlexMHllc** [comment]
Just noticed this after I went to another screen, then returned.
