### ISSUE TITLE
when navigating to facility manager the facility list closes, however sheets is open.  it should keep the state that it was used

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1268]
![image](https://user-images.githubusercontent.com/3675043/103052008-15397580-4566-11eb-9081-45fdfcf7cfef.png)

![image](https://user-images.githubusercontent.com/3675043/103052055-2b473600-4566-11eb-9d27-3dd673bb60d4.png)

it really needs to keep state.  by default it make sense that its closed but if I open one, it should remain open as I navigate because I'm on that facility and am moving around on that facility.  its frustrating to constantly reclick to reopen what I had already opened before but moved between task, issues etc.  basically we need to keep the user state once they select choose or other until they change that state much like how filters save state when you log out and log back in

**Comment by bluenevus** [comment]
this includes the page they were one.  for example I was on a task then clicked issues then when back to task and its back to the overview screen vs back where I left off

I would like to be where I left off as I navigate tabs then go back to a previous tab.  Its frustrating to reclick everything to get back to the same place I was one click ago

**Comment by LAlexMHllc** [comment]
Closing this without consistent tabs, since Facility Manager and Sheets do not have the exact same tabs on Facility Summary.
