### ISSUE TITLE
Facility Summary - Selecting Overdue and Not Overdue for Tasks and Issues did not update the Advanced filter

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1279]
Screenshot Example

![facility_manager_overdue_selections_not_update_advanced_filter](https://user-images.githubusercontent.com/11938477/103100761-317af800-45e2-11eb-8fef-853a453af6e8.png)

**Comment by bluenevus** [comment]
The word overdue should be capitalized Overdue like the rest AND Not Overdue should be called On Schedule

**Comment by LAlexMHllc** [comment]
See related Issue #1278
