### ISSUE TITLE
Facility Manager View:  UI Fix for Release Branch

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1285]
Fix bottom margin of center panel such that the bottom border of the last item (Task or Issue) is visible and not cut off.   
![image](https://user-images.githubusercontent.com/72885316/103111808-d7e4ee80-461e-11eb-9d5b-926809fbf7e2.png)

**Comment by LAlexMHllc** [comment]
Closing due to Issue #1592
