### ISSUE TITLE
risk milestone should be the task category as the milestone concept is NO more

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1293]
not a new enumeration
![image](https://user-images.githubusercontent.com/3675043/103228764-9181df00-48ff-11eb-9ab9-4fddeb25ef12.png)

but existing enumeration from task category

![image](https://user-images.githubusercontent.com/3675043/103228794-9e063780-48ff-11eb-8c13-30caafd20ce9.png)

**Comment by LAlexMHllc** [comment]
See related Issue #1241

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/103423742-49202680-4b76-11eb-8383-d72a600caf95.png)
