### ISSUE TITLE
the probability and impact of risks should only be 1-5

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1294]
![image](https://user-images.githubusercontent.com/3675043/103229272-b9257700-4900-11eb-930c-9f73522a5190.png)

not negative numbers

and not more than 5

else the priority won't calculate correctly and display on this heat map though we won't call it consequence, it should be called impact

we also need the plain language description next to the numbers like so in the enumeration and the heatmap so its plain as day to users

![image](https://user-images.githubusercontent.com/3675043/103229616-6bf5d500-4901-11eb-81b1-7e9721d1ad23.png)

**Comment by LAlexMHllc** [comment]
Range should be 1-5, not 0-5. Still need the plain language description next to the numbers (see above).
