### ISSUE TITLE
admin/projects - Advanced tab: Remove the first two enumerations for Task Stages and Issue Stages. Add enumeration for "Risk Stages in Project".

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1310]
Screenshot Example

![admin_project_forms_advanced_remove_first_two_stages](https://user-images.githubusercontent.com/11938477/103292193-593fd680-49bb-11eb-8ebc-1851392a09e3.png)

**Comment by LAlexMHllc** [comment]
Add enumeration for "Risk Stages in Project" and position after Issue Stages in Project.
Screenshot Example

![project_advanced_include_risk_stages_in_project](https://user-images.githubusercontent.com/11938477/103371228-e9098180-4a9c-11eb-8ca2-0ce4af6ca8f2.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/103418115-47953500-4b5b-11eb-970b-9e0545d6215e.png)
