### ISSUE TITLE
"Overdue" and "Not Overdue" (should be "On Schedule") filters are not functioning correctly, even with status selected.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1316]
When filters include "overdue" and "not overdue", no results found. Should have found all facilities.
Screenshot Example

![overdue_not_overdue_no_results_found](https://user-images.githubusercontent.com/11938477/103302599-09203e80-49d2-11eb-97a4-4cb0ad5d4f26.png)

**Comment by bluenevus** [comment]
The word is NOT "not overdue"
it should read "On Schedule"

**Comment by LAlexMHllc** [comment]
NOTE: When status is included in FLAG, then results found,

**Comment by LAlexMHllc** [comment]
Still has overdue task found with On Schedule filter.
Screenshot Example

![sheets_overdue_task_result_with_on_schedule_filter](https://user-images.githubusercontent.com/11938477/103363906-506a0600-4a8a-11eb-9dd7-47baef1d66ee.png)

**Comment by LAlexMHllc** [comment]
Map view screenshot examples

![map_active_overdue_on_schedule_not_functioning](https://user-images.githubusercontent.com/11938477/103368721-42ba7d80-4a96-11eb-97dd-1a15da051d93.png)

**Comment by microhealthamand** [comment]
It seems it is subject to order of execution. For now I have changed the execution to first check active or completed and then other filters

**Comment by LAlexMHllc** [comment]
The selected order should not matter for consistent results.
Screenshot Example

![overdue_not_overdue_selected_order_displays_inconsistent_results](https://user-images.githubusercontent.com/11938477/103420542-c8592e80-4b65-11eb-870b-86720d84b96c.png)

**Comment by LAlexMHllc** [comment]
Still needs to be fixed.
Screenshot Example

![active_on_schedule_incorrect_results](https://user-images.githubusercontent.com/11938477/103802813-b7a13080-501d-11eb-960c-fc75512c65f2.png)

**Comment by LAlexMHllc** [comment]
Closing since it functions when one or both selected without other filters, and another issue deals with combinations.
