### ISSUE TITLE
Facility Summary modal: selecting a facility status, due date, percentage complete, notes and tasks will update that information for all projects that facility is assigned to. Should be separate.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#133]
Screenshot Example

![facility_status__option_selected_becomes_status_all_facility_projects_2](https://user-images.githubusercontent.com/11938477/78385541-019a4900-75aa-11ea-9a80-e61c59dea267.jpg)

**Comment by bluenevus** [comment]
the developer can't understand what you are asking here.  you need to explain it better

**Comment by LAlexMHllc** [comment]
Updating project info for a facility on the Facility Summary modal should not change the info for all projects for a facility. Should be separate.

Screenshot Example

![facility_summary_modal_separate_project_info](https://user-images.githubusercontent.com/11938477/78828246-6858a180-79b2-11ea-9e45-ea62ecd06956.jpg)
![facility_summary_modal_separate_project_info_2](https://user-images.githubusercontent.com/11938477/78828397-a5bd2f00-79b2-11ea-8635-4006cd2b89aa.jpg)
