### ISSUE TITLE
Add Risks Module to Kanban View

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1331]

**Comment by bluenevus** [comment]
this is the kanban lanes

![image](https://user-images.githubusercontent.com/3675043/103358090-cbc7b980-4a82-11eb-8895-372a26d52b10.png)

**Comment by bluenevus** [comment]
we will need to add risk stage enumeration like we did on task and issues

**Comment by bluenevus** [comment]
we also need to figure out a better more consistent way to do this

![image](https://user-images.githubusercontent.com/3675043/103358183-f44fb380-4a82-11eb-90be-7c57b2fd7418.png)

so its more like this 

![image](https://user-images.githubusercontent.com/3675043/103358208-02053900-4a83-11eb-9ddd-eab47df100b5.png)
