### ISSUE TITLE
Add "Risks" section to ADVANCED FILTERS

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1335]
Screenshot Example

![advanced_filters_include_risks_section](https://user-images.githubusercontent.com/11938477/103368083-ac398c80-4a94-11eb-9990-bf29305832e1.png)

**Comment by LAlexMHllc** [comment]
Should be a Risks section on Advanced Filters with same filters as Risks tab under Issue #1302

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/104351785-d39c4a80-54d3-11eb-9446-d8abfda95938.png)
