### ISSUE TITLE
Facility listed that matched Action User filter, but did not match filter for status.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1336]
Screenshot Example

![advanced_filter_selected_user_with_active](https://user-images.githubusercontent.com/11938477/103369386-00923b80-4a98-11eb-9148-1ea2fe7e9bc7.png)

![advanced_filter_selected_user_with_active_facility_with_user_but_complete_task_not_active](https://user-images.githubusercontent.com/11938477/103369396-038d2c00-4a98-11eb-9b5e-59c4dbb8caae.png)

**Comment by microhealthamand** [comment]
The business logic first checks the status filter and then checks the user filter. So it will show the result accordingly
