### ISSUE TITLE
Project Dashboard - Facility Groups modal: Each facility group should display and have an indication whether status is active or inactive.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#135]
Presently, if a facility group is inactive it will not display on the Facility Groups modal, but their facilities are included in the count.

All facility groups should display, but just indicate whether the status is active or inactive.

**Comment by LAlexMHllc** [comment]
NOTE: If the inactive facility groups are to remain not displayed, then there is no need to display facility group status.

Then below the facilities count (top of modal) the total active and total inactive should display instead.

**Comment by LAlexMHllc** [comment]
Screenshot Example

![project_summary_modal_facility_groups_include_inactive](https://user-images.githubusercontent.com/11938477/83298423-6d6feb00-a1c2-11ea-8571-184cbff4353b.png)

**Comment by bluenevus** [comment]
Any inactive cannot be rolled up into totals or numbers else it will mess up tracking the project that are active

[cid:image008.png@01D635CF.DFFED2D0]
Frank Tucker​
Chief Executive Officer
,
Executive Office
t: 855‑294‑3547
m: 571-327-1211<tel:571-327-1211>
frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
 |
www.microhealthllc.com<https://www.microhealthllc.com/>
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
[Twitter]<https://twitter.com/microhealthllc?lang=en>
[Facebook]<https://www.facebook.com/microhealthllc/>
[YouTube]<https://www.youtube.com/user/microhealthtube>
[LinkedIn]<https://www.linkedin.com/company/microhealth-llc>
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by LAlexMHllc** [comment]
If "inactive" Facility Groups are not to display on the Project Summary modal - Facility Groups section, then remove "active" from the facility group listings.
