### ISSUE TITLE
project was configured with select stages but instead of showing only those stages, it shows every stage

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1398]
this is what the drop down looks like 

![image](https://user-images.githubusercontent.com/3675043/103906711-4e2d2a80-50ce-11eb-934b-b61ed5990f49.png)

this is what was configured and what should actually show

![image](https://user-images.githubusercontent.com/3675043/103906821-6d2bbc80-50ce-11eb-8f7f-d7363a9c0cac.png)

**Comment by bluenevus** [comment]
we need to double check to make sure all the selected project enumerations only show in the project it was assigned

**Comment by LAlexMHllc** [comment]
Examples from Dev

Screenshot of Temp Project - Advanced tab - enumerations

![temp_project_stages](https://user-images.githubusercontent.com/11938477/103917919-2775f080-50dc-11eb-94aa-5e36de5d72bf.png)

Screenshot of ADVANCED FILTERS for Task Stages and Issue Stages
![temp_project_task_and_issue_stages](https://user-images.githubusercontent.com/11938477/103917623-d0701b80-50db-11eb-846c-2e39fc9c97cc.png)

Screenshot of Kanban view
![temp_project_kanban_tabs](https://user-images.githubusercontent.com/11938477/103917663-de25a100-50db-11eb-9aad-2494ba22be25.png)

**Comment by LAlexMHllc** [comment]
Example Screenshot of Dev when Task Stages and Issue Stages were not selected for enumerations

![testing123_empty_task_issue_stages](https://user-images.githubusercontent.com/11938477/103922309-90ac3280-50e1-11eb-9caf-9ad71fb4e12c.png)
