### ISSUE TITLE
Facility form - Due date year options: Remove 2015 through 2019 and Add 2026 through 2030

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#143]
Screenshot Example

![facility_due_date_options](https://user-images.githubusercontent.com/11938477/78823999-a3a3a200-79ab-11ea-8692-b8d2c49268fc.jpg)

**Comment by bluenevus** [comment]
probably just needs to be a regular calendar field type of date.  I'm worried as time goes on that we always start at 2020.  next year we have the same issue

I get that they need to be able to go back in time probably not that far but I don't want to limit them to put histoical info should they want.   Projects can be more than 10 years out so they need to pick something greater

a regular calendar with the default of today would suffice and make it easier

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8229 Boone Blvd, Suite 500  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________

**Comment by bluenevus** [comment]
The other problem is the due date itself.  The facility doesn't have a due date, the project has a due date.  so the best thing is to remove it from here

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8229 Boone Blvd, Suite 500  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________

**Comment by bluenevus** [comment]
also, the facility doesn't have a status, the project has a status so best to remove it from here

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8229 Boone Blvd, Suite 500  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________
