### ISSUE TITLE
Admin/Facility: Remove (project) Status and (project) Due date from this the New Facility form and Edit Facility form.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#144]
Admin Panel: Remove status and due date from the Add Facility and Edit Facility forms.

Screenshot Example

![remove_status_due_date_from_admin_facility_forms](https://user-images.githubusercontent.com/11938477/78897879-de0b4e80-7a40-11ea-8ca1-7bdbecf4f6c3.jpg)

**Comment by bluenevus** [comment]
This isn't for just the facility.  Each one of those are for projects so they just need to be removed.  Projects have status at a specific site.  Projects have due dates for a specific site.  A site doesn't have one status and one due date for all projects

Sent from my Verizon, Samsung Galaxy smartphone

________________________________
