### ISSUE TITLE
1302f: Add Risk Matrix legend at bottom of Risk form

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1489]
Display risk matrix as legend at the bottom and color code the priority level to match the matrix. we won't be calling it consequence as its called Impact.

Change headers:
Consequence to **Impact**
Likelihood to **Probability** 
![D988C0E2-9EAD-4CF3-A7A3-814AF644F4BA](https://user-images.githubusercontent.com/72885316/104812863-398a1a00-57d3-11eb-8a75-3960790e51ec.jpeg)

**Comment by LAlexMHllc** [comment]
P3-I3 High 12 should be orange
P3-C5 Extreme 14 should be Extreme 15
