### ISSUE TITLE
Deprecate Facility Manager 

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1592]
- Sheets will become default page for general project management.
- Rename **Sheets** to **Manage** in tabbar (navbar)
- Reorder tabbar (navbar) items starting with Map, followed by Manage
- Ensure nav route also gets changed (e.g. no longer this: **_http:...../projects/1/sheets_**; instead, this: _**http:...../projects/1/manage**_

**Comment by bluenevus** [comment]
bye
