### ISSUE TITLE
Clicking user email on header bar of Client Panel does not display the user's account

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#160]
Screenshot Example

![client_paneLclick_user_email_display_user_account](https://user-images.githubusercontent.com/11938477/81220088-bf9c6280-8fae-11ea-9aff-665f50d0da1d.jpg)

**Comment by bluenevus** [comment]
they really need to see their account info and be able to update it particularly their passwords.

**Comment by bluenevus** [comment]
Password complexity needs to be 16 characters with at least 1 special character, one number, and one capital letter

**Comment by LAlexMHllc** [comment]
User Account form should have the following (all editable, except email).

![user_account_form](https://user-images.githubusercontent.com/11938477/81220584-8c0e0800-8faf-11ea-9130-446b8ebdaa0c.jpg)
