### ISSUE TITLE
Client Panel:  Make Map View the default landing page 

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1608]
Currently, Manage is the default landing page.  Change this to Map View.

**Comment by bluenevus** [comment]
we don't want the default map view.  Everyone works in manage so we should stay in manage.

**Comment by bluenevus** [comment]
also there is a requirement for the future that allows people to customize their default landing.  until then leave it on the manage page

**Comment by juan-rivera-2020** [comment]
Sounds good.  Closing issue now.
