### ISSUE TITLE
Client Panel:  Design Map View Project Summary consistent with new Project Overview page

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1609]
**Current view of Map side Project Summary:**
![image](https://user-images.githubusercontent.com/72885316/106289258-0f931780-6217-11eb-868e-a596cc0e36da.png)

**Change Project Summary design to something consistent with this:** 
New layout will allow users to get full view of project summary (i.e. Tasks, Issues, Risks) while reducing or eliminating the need to scroll.
![image](https://user-images.githubusercontent.com/72885316/106289565-67ca1980-6217-11eb-9a2b-7146dbcf4253.png)

**Comment by LAlexMHllc** [comment]
See related Issues #1624 and #1625
