### ISSUE TITLE
if you pick a category that doesn't apply you get a blank screen and can't change it without going to advanced filters

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1620]
![image](https://user-images.githubusercontent.com/3675043/106357371-b9d07500-62d3-11eb-9c06-ff9cb3b97954.png)

**Comment by LAlexMHllc** [comment]
The app was updated, and the Program Summary for 0 Projects now displays. User still has to go to Advanced Filters.
Screenshot Example

![Program_Summary_0_projects](https://user-images.githubusercontent.com/11938477/109543471-51241600-7a94-11eb-876c-b84694ea9510.png)

**Comment by LAlexMHllc** [comment]
Closing, since Issue #2252 opened
