### ISSUE TITLE
Map view - Possible for full screen world to not repeat?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1629]
Screenshot Example

![full_screen_map_view](https://user-images.githubusercontent.com/11938477/106510268-b4725680-649c-11eb-8043-bf6c6b45a2dd.png)

**Comment by christopherandrewcalderon** [comment]
@LAlexMHllc It is possible. However, there is a media query that occurs with the Google Map component where if the viewport width is above/below a certain threshold, the map zoom will be restricted. 

What size is the viewport width this screenshot was taken on?

**Comment by LAlexMHllc** [comment]
Closing, never mind. Users probably won't use the full screen feature.
