### ISSUE TITLE
Search Risks does not filter correctly; always no found result.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1643]
User searched Risks on Manage and Kanban views.
Screenshot Example

![search_risks_not_functioning](https://user-images.githubusercontent.com/11938477/106658902-ed2d3100-656b-11eb-9507-1a755d3da0cd.png)

**Comment by LAlexMHllc** [comment]
Search Risk does not function on Map, Sheet, or Kanban views.

**Comment by juan-rivera-2020** [comment]
Confirmed Kanban was not working.  Just fixed it.  Map and Sheet searches were functioning with no issues, however.
