### ISSUE TITLE
Project Summary - Overview: Should make it clear that Categories is a filter.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1652]
Screenshot Example

![overview_categories_filter](https://user-images.githubusercontent.com/11938477/106785581-86ffe700-661b-11eb-9c26-ee1542f06969.png)

**Comment by bluenevus** [comment]
probably should be moved to the filter section here since that is what it does
![image](https://user-images.githubusercontent.com/3675043/107390230-7ccf6400-6ac5-11eb-99b7-591ae008fad5.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![summary_move_categories_selector_to_filters](https://user-images.githubusercontent.com/11938477/109693575-d15f7f80-7b57-11eb-9b73-54b764ef121e.png)

**Comment by LAlexMHllc** [comment]
See related Issues #1632, #1641, #1663, and #1671

**Comment by LAlexMHllc** [comment]
Closing, since Categories selection was removed from Overview tab.
