### ISSUE TITLE
Sheet and export "Assigned Users" header change (ref:RACI)

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1665]
For Sheet view and the exports, is it safe to assume that **Assigned Users** column header will be changed to **Responsible**? This means that the displayed data will go from listing multiple users to just one _Responsible_ user.  Will this differ from Task, Issue, Risk?

**Comment by LAlexMHllc** [comment]
NOTE: Presently, Responsible is a multi-select drop-down.
See screenshot in Issue #1668

**Comment by LAlexMHllc** [comment]
NOTE: Tasks and Issues have RACI for Assigned Users as well. See Issue #1692

**Comment by curtismayer** [comment]
No the column headers should not be changed but remain as Assigned Users.  However, next to every name needs to be R, A, C, or I.
