### ISSUE TITLE
Add a link to online help to the main menu

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mGis#1666]
In the main menu add a Help menu item between the Admin/Client Panel and the Welcome message ... 

![image](https://user-images.githubusercontent.com/67476905/107047184-8723f200-6795-11eb-93a5-86288fc7d4da.png)

The Help menu item should like to ./Help/home.htm

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/107058336-7c238e80-67a2-11eb-94b2-2d3ae9d690ab.png)

**Comment by LAlexMHllc** [comment]
Help link missing

Screenshot Example

![missing_help_link](https://user-images.githubusercontent.com/11938477/107242345-e124f180-69f9-11eb-8f1a-6a63ed8cea9c.png)

**Comment by LAlexMHllc** [comment]
NOTE: "Help" is not listed under Privileges for User, so that is not the reason the Help link does not display.
