### ISSUE TITLE
No indicators for RACI under Assigned Users 

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1692]
Screenshot Example

![assigned_users_no_indicators_RACI](https://user-images.githubusercontent.com/11938477/107268407-150e1000-6a16-11eb-96ba-94b58cc5465f.png)

**Comment by curtismayer** [comment]
I think it would be good to add (R), (A), (C), (I) after each name to identify each users role without taking up to much landscape in the table.
