### ISSUE TITLE
Tasks - Add button to move tasks

### ISSUE THREAD

**Issue by christopherandrewcalderon** [MicroHealthLLC/mGis#1693]
From the sheets view page/modal, add button to move task to another project.

**Comment by LAlexMHllc** [comment]
NOTE: This was only done on Map view, not Sheet view.

**Comment by christopherandrewcalderon** [comment]
@LAlexMHllc There is a bug with our UI library that prevents the drop-down from manifesting within the modal. Looking for a fix.

**Comment by LAlexMHllc** [comment]
NOTE: Move now done by right-click on Sheet view (preferred method).
MOVE missing from Map and Kanban views.
