### ISSUE TITLE
if I added a task, issue risk etc from a project then the default project should be the one already selected

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1714]
if I added a task, issue risk etc from a project then the default project should be the one already selected

however project is blank

![image](https://user-images.githubusercontent.com/3675043/107530319-c1bcce80-6b89-11eb-80e6-f55b6a7e6f12.png)

**Comment by LAlexMHllc** [comment]
Duplicate to Issue #1654

**Comment by LAlexMHllc** [comment]
NOTE: The Add forms still do not have the current project selected by default.
Screenshot Example

![current_project_should_be_selected_by_default_on_add_forms](https://user-images.githubusercontent.com/11938477/108367450-79c02c00-71c7-11eb-8488-7fbd235a3eef.png)

**Comment by LAlexMHllc** [comment]
Closing, since select Project removed from forms
