### ISSUE TITLE
"Move" button on form has the same function as selecting "Project", so not necessary.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1716]
Clicking "Move", then selecting a project has the same function as selecting "Project" on form. As per Issue #947, Project should be search/select and moved to the top of the form.

Screenshot Example

![move_button_project_select_same_function](https://user-images.githubusercontent.com/11938477/107534068-8fad6b80-6b8d-11eb-9ff4-132e561f19eb.png)

**Comment by LAlexMHllc** [comment]
NOTE: Unless "Project" is going to removed from the form, why is "Move" necessary?
Also, can "Move" become search/select?

**Comment by bluenevus** [comment]
I would rather have the move than the project selector not both.  because the action is really a move to a different project

its way to easy to change a task to a different project then lose the task and not be able to find it

**Comment by LAlexMHllc** [comment]
Closing, since Move will replace Project select.
