### ISSUE TITLE
Project should be removed from all CRUD pages (the one use for move)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1719]
"Project" is enabled on edit form. User should have to use "Move" instead.
Screenshot Example

![task_edit_form_project_should_not_be_selectable](https://user-images.githubusercontent.com/11938477/107550954-ad83cc00-6b9f-11eb-89b0-cbd9594a2be5.png)

**Comment by curtismayer** [comment]
Additionally, Move has been removed from action bar and right-click on Sheet is the preferred method.

**Comment by LAlexMHllc** [comment]
QUESTION: If "Project" is removed from Add forms, then how will user select project when entering data at the Project Group level?
See Issue #1037

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/108526228-dfcbb280-729e-11eb-99b6-905e42bc3326.png)

![image](https://user-images.githubusercontent.com/74916983/108526296-f1ad5580-729e-11eb-96de-60a02ef7bf0d.png)
