### ISSUE TITLE
Add the ability to enter the progress of a checklist 

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mGis#1733]
See attached enhancement request document.
[IT Apps Enhancement Request - Checklists.docx](https://github.com/MicroHealthLLC/mGis/files/5970000/IT.Apps.Enhancement.Request.-.Checklists.docx)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/107830149-3abe5080-6d59-11eb-9928-99dfcb451eb5.png)
