### ISSUE TITLE
Provide ability to show/hide Consulted and Informed users in the Assigned To column

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1735]
Screenshot Example

![all_consulted_and_informed_should_display_assigned_users](https://user-images.githubusercontent.com/11938477/107782694-5ef93d80-6d17-11eb-8194-fb555306c8b6.png)

**Comment by juan-rivera-2020** [comment]
Do we really want all the additional Consulted and Informed users to be displayed?   The way I configured it was for just just one Consulted and Informed user to be displayed (to conserves space) (by design, not a bug).    If we want all additional users to be displayed, one row, could take up a disproportional amount of height.

**Comment by LAlexMHllc** [comment]
SUGGESTION: When more than one user for Consulted or Informed, could include a more icon after the name. When user clicks the more icon, toggle the other users.

**Comment by LAlexMHllc** [comment]
NOTE: Presently, since only the first selected user gets displayed, when you want a newly selected user to display on the table, you have to remove all, then reselect that user first.

**Comment by curtismayer** [comment]
Actually we should have it just be Responsible and Accountable displayed in the Sheet and Export.  They can go to the details to see who was consulted and/or informed.  If any of our mgis users then complain about not seeing all the users we can add a toggle somewhere to show Consulted and Informed as well, but we will deal with that if it arises.

**Comment by curtismayer** [comment]
We will add a toggle button (Show/Hide Consulted and Informed) or checkbox (Show Consulted and Informed) next to the export icons
