### ISSUE TITLE
Admin/Facilities screen: Tasks filter has options for every task created, whether it still exists or not. Should this exists here, and if yes, then with what function?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#178]
Screenshot Example

![admin_facilities_task_filter](https://user-images.githubusercontent.com/11938477/79780361-cc139080-8309-11ea-88c9-369ff052252a.jpg)

**Comment by bluenevus** [comment]
There could be thousands of tasks.  This might be better as a search term vs dropdown

**Comment by LAlexMHllc** [comment]
Should this be changed to "Task Type"? When selected, facilities with that task type will display.

**Comment by bluenevus** [comment]
Task type is indeed a drop down

**Comment by LAlexMHllc** [comment]
How about "Task Type" as drop-down (to narrow down search textbox) with Task search textbox.

Screenshot Example

![facilities_screen_task_filters](https://user-images.githubusercontent.com/11938477/79782997-f6ffe380-830d-11ea-9ca5-338a8d7823fe.jpg)
