### ISSUE TITLE
Modal and Saving:  Saving form should not close edit session

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1805]
One main problem affecting the mGIS UX is the automatic closure of the form upon saving.  The form should only close if the user wants the form to close (ie, "Close" button).  The automatic closure is also occurring when the **On Watch** checkbox is toggled.  The form should not automatically close if the user checks  or unchecks the **On Watch** box.    

We have begun work to remove the modal from the client panel.  It's important to note that only Kanban view uses the modal library in question.  However, in troubleshooting this issue, we have discovered that the Kanban view Task form is the only form that behaves as desired.  That is, it saves user's editing/creating data without closing the form.   The Kanban Risk and Issue forms do not behave consistent with the Kanban Task form, an inconsistency which we also need to fix.  

Resolving this issue will address the undesired saving behavior in Sheet view, Map view, and Kanban Risks and Issues view.

**Comment by LAlexMHllc** [comment]
Task, Issue and Risk forms close when Save clicked

**Comment by LAlexMHllc** [comment]
Map view - Tasks, Issues, and Risks still need to be fixed.

**Comment by juan-rivera-2020** [comment]
Will create new issue for Map View as Sheet View was priority for this release.

**Comment by juan-rivera-2020** [comment]
Implemented in Sheet and Kanban view.
