### ISSUE TITLE
Map and Kanban views - Task - Checklist item: Fix Due Date

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1859]
Screenshot Example

![fix_Due_Date_Task_Checklist_Item_Kanban_and_Map](https://user-images.githubusercontent.com/11938477/109197196-b3b2a480-776a-11eb-8284-65a1d4888872.png)

**Comment by juan-rivera-2020** [comment]
Fixed in Kanban view (deployed to QA).  Map view fix in progress.

**Comment by LAlexMHllc** [comment]
Due Date now missing in Kanban view.
See Issue #1886
