### ISSUE TITLE
move category selection on the dashboard from the project group to the Filters group

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1863]
as a user, I'm confused on the categories thinking I need to enter data for it when its a filter

![image](https://user-images.githubusercontent.com/3675043/109215977-e9af5300-7781-11eb-96d3-3870eeb53956.png)

move to 

![image](https://user-images.githubusercontent.com/3675043/109215985-ef0c9d80-7781-11eb-9a57-77cfb642e562.png)

**Comment by LAlexMHllc** [comment]
Same as Issue #1652

**Comment by LAlexMHllc** [comment]
Closing, since Categories selection was removed from Overview tab.
