### ISSUE TITLE
Program Summary - Issues section: Missing Categories listing and Issue Types subhead

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1903]
Fix on Map and Sheet views
Screenshot Example

![program_summary_issues_section](https://user-images.githubusercontent.com/11938477/109695780-5055b780-7b5a-11eb-9e11-3a0bfbf323da.png)

**Comment by LAlexMHllc** [comment]
See related Issues #1902 and #1904

**Comment by LAlexMHllc** [comment]
Still not fixed.
Screenshot Example of Sheet view

![sheet_view_program_summary_issues_missing_categories_issue_types_subhead](https://user-images.githubusercontent.com/11938477/110814001-073aed00-8257-11eb-921b-fcceec610a49.png)

Screenshot Example of Map view

![map_view_program_summary_issues_missing_categories_issue_types_subhead](https://user-images.githubusercontent.com/11938477/110814061-16219f80-8257-11eb-8e32-afeca8aef878.png)

**Comment by juan-rivera-2020** [comment]
Recent fix for #1971 fixed this issue.
