### ISSUE TITLE
Kanban view - No stage Column should not be shown when there are one or more stages present

### ISSUE THREAD

**Issue by bilel-kedidi** [MicroHealthLLC/mGis#1909]
<img width="1318" alt="Screenshot 2021-03-03 at 8 21 10 PM" src="https://user-images.githubusercontent.com/5988861/109828887-dbb87100-7c5e-11eb-831b-5ea950cc30af.png">

**Comment by LAlexMHllc** [comment]
Closing. This is the drag card off of Kanban area
