### ISSUE TITLE
Fix the position of Issues Export and show/hide Consulted and Informed buttons when user does not have Write privilege

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1921]
Screenshot Example

![issues_tab_fix_position_buttons_user_without_Write_privilege](https://user-images.githubusercontent.com/11938477/110018291-2684c800-7cf5-11eb-9c2d-9758d895b488.png)

**Comment by juan-rivera-2020** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/72885316/110506673-505f3580-80cd-11eb-8666-0c9223286390.png)
