### ISSUE TITLE
admin/projects form validation message should have "Project name" instead of "Facility name"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1975]
Screenshot Example

![admin_project_form_validation_text](https://user-images.githubusercontent.com/11938477/106035704-6a573280-60a2-11eb-9f38-ea5bfaceb350.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/111221651-27e5a880-85b1-11eb-8ef3-3043aa5a5435.png)
