### ISSUE TITLE
Project dashboard - Facility Summary modal: Subscriber should ONLY be able to edit/delete THEIR notes.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#201]
Screenshot Example

![facility_summary_modal_only_note_creator_edit_delete](https://user-images.githubusercontent.com/11938477/80222165-6a5a6b80-8614-11ea-8577-0ac5bcabe3ef.jpg)

**Comment by bluenevus** [comment]
Well the person that entered the note should be the only one allowed to edit or delete their note

That is NOT the case for tasks.  Subscribers can edit or delete others tasks there.
