### ISSUE TITLE
when I navigate from one project to another, these filters should be per program

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#2020]
The problem is that when I am in program a, the filters are set for that program, when I then go to program b, those filters can make it look like there are not projects in that program because the filters were set for program a

Therefore, these filters should be per program and when you change programs, the last filter you used for that program should persist

![image](https://user-images.githubusercontent.com/3675043/111018511-2fc20480-8387-11eb-9661-4d8bbed24d97.png)

**Comment by LAlexMHllc** [comment]
Still needs to be fixed. The last filter used for a program should persist on return, instead of filter reset to default.
