### ISSUE TITLE
Index - Sign Up Form: Missing "First Name" and "Last Name", so clicking "Signup" displays errors.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#206]
Screenshot Example

![index_signup_form_missing_first_name_last_name_receive_errors](https://user-images.githubusercontent.com/11938477/80415508-a570cf00-88a0-11ea-83a8-24b2506853a4.jpg)

**Comment by bluenevus** [comment]
We need to disable sign up

Don’t want it
