### ISSUE TITLE
Sheet view - Risks forms should be full width for all tabs and should display above sheet table

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#2066]
Screenshot Example of Add Risk

![risk_forms_full_width_all_tabs](https://user-images.githubusercontent.com/11938477/111477087-21684580-8705-11eb-959c-1c1084ab5f73.png)

**Comment by LAlexMHllc** [comment]
Screenshot of Edit Risk

![risk_forms_full_width_all_tabs_above_sheet_table](https://user-images.githubusercontent.com/11938477/111477842-e6b2dd00-8705-11eb-96fc-69153e249353.png)

![risk_forms_full_width_all_tabs_above_sheet_table_2](https://user-images.githubusercontent.com/11938477/111478397-6e005080-8706-11eb-9018-d1a14a1fd6f9.png)

**Comment by juan-rivera-2020** [comment]
Moving to 'Deployed to QA" column and closing as this issue was identified and fixed in #2064
