### ISSUE TITLE
Project Status should have "Not Started" by default

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#2080]
Project Status reverted to default none selected.
Screenshot Example

![project_status_should_have_Not_Started_default_instead_none_selected](https://user-images.githubusercontent.com/11938477/111520262-51780e80-872e-11eb-9b7a-a684b660f4ad.png)

**Comment by microhealthamand** [comment]
Status select box is showing list of statuses of Program which we can set in admin Program edit form, is that expected? Or do we want to show the status of Project which is connected with Program?

**Comment by microhealthamand** [comment]
https://github.com/MicroHealthLLC/mGis/issues/2081

**Comment by LAlexMHllc** [comment]
Closing, see Issue #2143
