### ISSUE TITLE
Task/Issue Form - Scroll point in middle

### ISSUE THREAD

**Issue by christopherandrewcalderon** [MicroHealthLLC/mGis#2106]
For both the Task and Issue Forms, the scroll point is located below the "* Indicates required fields" text. This differs from the Risk Form which has the scroll point at the top of the form.

![image](https://user-images.githubusercontent.com/77029475/111817996-e9dfd180-889b-11eb-9b1a-99801473c288.png)

**Comment by LAlexMHllc** [comment]
Closing, since Risk form scroll point was updated to match Task and Issue
