### ISSUE TITLE
not sure if this is a work in progress toward a specific purpose but as it stands...its doesn't really make sense

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#2114]
![image](https://user-images.githubusercontent.com/3675043/111877183-7495fe80-8978-11eb-94a9-dd8ec1640114.png)

and I can't seem to upload files

this doesn't do anything either

![image](https://user-images.githubusercontent.com/3675043/111877262-e0786700-8978-11eb-9970-93906e718a55.png)

**Comment by LAlexMHllc** [comment]
Include placeholder text for file hyperlink textbox.
Screenshot Example

![include_placeholder_text_for_file_hyperlink_textbox](https://user-images.githubusercontent.com/11938477/112046772-d5613a80-8b22-11eb-84ec-49b85fb7e12f.png)
