### ISSUE TITLE
Update the Control tab on Risks

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mGis#2139]
On Risks:

Create a Files tab
- Add a Files tab that appears after the Control tab but before the Disposition tab
- On the Files tab, update the files uploaded listing to be above the "drop files here" box, but below the linked listing
- Remove Files functionality from the Control tab

Create a Related tab
- Add a Related tab that appears after the Files tab but before the Disposition tab 
- Update the Related tab with the Related functionality
- Remove the Related functionality from the Control tab	

Create an Updates tab
- Add an Updates tab that appears after Disposition
- Update the Updates tab with the Updates functionality
- Remove the Updates functionality from the Control tab

**Comment by LAlexMHllc** [comment]
Closing, see Issue #2157 for Files tab issues.
