### ISSUE TITLE
change the stage from a dropdown to a graphical selection

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#2161]
from this 

![image](https://user-images.githubusercontent.com/3675043/112347946-b5a25180-8c9d-11eb-9d74-99d071fb0d12.png)

to more like this 

![image](https://user-images.githubusercontent.com/3675043/112348281-0fa31700-8c9e-11eb-9c03-26186a2cb052.png)

where they can select and clearly know where they are at in the stage

**Comment by juan-rivera-2020** [comment]
Based on image examples above, would the graphical selection be a tabbed component?  If so, each tab would include a stage name and stage description?  At the moment, stages only have one attribute (ie, percentage).  Do we want to expand the stage model to include other values like stage description?

Or do we simply want the selection to be represented by a step component like so (here are two examples): 
![image](https://user-images.githubusercontent.com/72885316/113018266-5ab1a400-914e-11eb-9597-1c9abbc1880f.png)
