### ISSUE TITLE
Routes - Configure Rails Routes for Vue Router

### ISSUE THREAD

**Issue by christopherandrewcalderon** [MicroHealthLLC/mGis#2204]
In order to maintain more better context throughout the application, the following routes are going to be added to the Vue front-end:

**Currently the base URL is utilizing "projects" and not "programs". The base URL will also need to be changed.*

##### Map Routes
- /programs/:programId/map/projects/:projectId

- /programs/:programId/map/projects/:projectId/tasks
- /programs/:programId/map/projects/:projectId/tasks/:taskId

- /programs/:programId/map/projects/:projectId/issues
- /programs/:programId/map/projects/:projectId/issues/:issueId

- /programs/:programId/map/projects/:projectId/risks
- /programs/:programId/map/projects/:projectId/risks/:riskId

- /programs/:programId/map/projects/:projectId/notes
- /programs/:programId/map/projects/:projectId/risks/:noteId
___
##### Sheet Routes
- /programs/:programId/sheet/projects/:projectId

- /programs/:programId/sheet/projects/:projectId/tasks
- /programs/:programId/sheet/projects/:projectId/tasks/:taskId

- /programs/:programId/sheet/projects/:projectId/issues
- /programs/:programId/sheet/projects/:projectId/issues/:issueId

- /programs/:programId/sheet/projects/:projectId/risks
- /programs/:programId/sheet/projects/:projectId/risks/:riskId

- /programs/:programId/sheet/projects/:projectId/notes
- /programs/:programId/sheet/projects/:projectId/risks/:noteId
___
##### Kanban Routes
- /programs/:programId/kanban/projects/:projectId

- /programs/:programId/kanban/projects/:projectId/tasks
- /programs/:programId/kanban/projects/:projectId/tasks/:taskId

- /programs/:programId/kanban/projects/:projectId/issues
- /programs/:programId/kanban/projects/:projectId/issues/:issueId

- /programs/:programId/kanban/projects/:projectId/risks
- /programs/:programId/kanban/projects/:projectId/risks/:riskId

**Comment by microhealthamand** [comment]
Implemented

/programs/1/map
/programs/1/sheet
/programs/1/kanban
/programs/2/gantt
/programs/1/member_list

**Comment by christopherandrewcalderon** [comment]
@microhealthamand Could you please add the following routes in Rails:

##### Map Routes

- /programs/:programId/map/projects/:projectId/tasks/new
- /programs/:programId/map/projects/:projectId/issues/new
- /programs/:programId/map/projects/:projectId/risks/new
- /programs/:programId/map/projects/:projectId/notes/new

___
##### Sheet Routes

- /programs/:programId/sheet/projects/:projectId/tasks/new
- /programs/:programId/sheet/projects/:projectId/tasks/new

___
##### Kanban Routes

- /programs/:programId/kanban/projects/:projectId/tasks/new
