### ISSUE TITLE
Client Panel:  Add Overflow-Y property on select pages

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#2257]
The recent fix to remove the vertical wiggle in Client Panel pages and forms introduced the need to adjust height settings in other pages.  Pages (eg, Login page, Team page, etc.) require the overflow property set such that the vertical scroll bar is present when required.

**Comment by LAlexMHllc** [comment]
Closing, since done on most screens.
See Issue #2300 for users/sign_in screen.
