### ISSUE TITLE
instead of "show" as the link can the title hyperlink to the project?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#228]
![image](https://user-images.githubusercontent.com/3675043/80759839-f2a1aa80-8b05-11ea-9857-c001503c8bbe.png)

**Comment by LAlexMHllc** [comment]
For each project:
Make each project name a hyperlink; when clicked display corresponding Project Dashboard; remove the "show" link.

Screenshot Example

![dashboard_user_projects_links](https://user-images.githubusercontent.com/11938477/81191119-a97aac00-8f86-11ea-8133-9ad22fb5d449.jpg)
