### ISSUE TITLE
facility groups do not require a color code and should be removed

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#229]
![image](https://user-images.githubusercontent.com/3675043/80760370-cb97a880-8b06-11ea-85d8-d099fe7a3be9.png)

**Comment by LAlexMHllc** [comment]
Facility Group - remove "Color" from:
- New and Edit forms
- Table column
- Filter form

Screenshot Examples

![facility_group_forms_remove_color](https://user-images.githubusercontent.com/11938477/81189377-7c2cfe80-8f84-11ea-9048-cb39962a5d30.jpg)

![remove_facility_group_table_color_column_filter_color](https://user-images.githubusercontent.com/11938477/81189390-7fc08580-8f84-11ea-95ba-8b21d83ee0e2.jpg)
