### ISSUE TITLE
status should be color coded IF that color code can be the same color as the push pins on google maps

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#230]
status should be color coded IF that color code can be the same color as the push pins on google maps

This way the user can see what status each facility is based on the color of the push pin on the map

![image](https://user-images.githubusercontent.com/3675043/80760440-e9650d80-8b06-11ea-800e-0040357f581d.png)

**Comment by LAlexMHllc** [comment]
Example: 

https://medium.com/free-code-camp/how-to-change-javascript-google-map-marker-color-8a72131d1207
