### ISSUE TITLE
Edit User Profile - Update Program "Search and select Program" option links from /projects to /program.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#2306]
Screenshot Example

![profile_update_Program_search_and_select_option_links_from_project_to_program](https://user-images.githubusercontent.com/11938477/114718675-389a5300-9d04-11eb-9f5a-f5735d290542.png)
![profile_update_Program_search_and_select_option_links_from_project_to_program_2](https://user-images.githubusercontent.com/11938477/114718753-510a6d80-9d04-11eb-9c3c-0ed070c3076e.png)

**Comment by microhealthamand** [comment]
Related #2315 #2311 #2312
