### ISSUE TITLE
don't automatically zoom into the map when clicking a push pin

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#231]
currently when you click the push pin for the first time it will automatically zoom in.  Since there are multiple sites what ever zoom level they are at should remain because they will want to cycle through different sites.  right now you have to zoom out then click another site

![image](https://user-images.githubusercontent.com/3675043/80760692-4e206800-8b07-11ea-840f-93e48a58e0d4.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![map_click_facility_push_pin_no_autozoom_map](https://user-images.githubusercontent.com/11938477/81192775-9b2d8f80-8f88-11ea-81d3-4cb1b6e7eb9f.jpg)
