### ISSUE TITLE
google authentication not working.  after logging in it takes me back to the login screen

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#233]
![image](https://user-images.githubusercontent.com/3675043/80820632-457e6f00-8ba5-11ea-86f0-a379c771b06f.png)

then when I log out then log back in using my microsoft sso I get this error message

![image](https://user-images.githubusercontent.com/3675043/80820676-59c26c00-8ba5-11ea-9989-f86ac3c17bdd.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/81321735-f7fc7900-9060-11ea-8834-ea91a63162d2.png)

I think the issue may be the callback url possibly?  

users/auth/google_oauth2/callback

**Comment by bilel-kedidi** [comment]
fixed by updating Gemfile
