### ISSUE TITLE
Risk Approach Approved checkbox does not remain checked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#2375]
Success message displayed after Risk Approach Approved checkbox was checked. Regardless if the user clicks Save or Close, when Edit that risk again, the checkbox is unchecked.

Screenshot Example of Prioritize tab with message, then Close clicked

![risk_approver_test_1_approved_section_approved_checked_success_message_disabled_fields_close](https://user-images.githubusercontent.com/11938477/115596910-a7e4e980-a2a6-11eb-8e53-85dd87d89904.png)

User Edit Risk again, checked Approved checkbox again, then clicked Save
Screenshot Example

![risk_approver_test_1_approved_section_approved_checked_success_message_disabled_fields_save](https://user-images.githubusercontent.com/11938477/115596948-b3381500-a2a6-11eb-87fc-db481c5ab6c6.png)

User Edit Risk again, and the checkbox was still unchecked
Screenshot Example

![risk_approver_test_1_approved_section_approved_checkbox_not_stick_checked](https://user-images.githubusercontent.com/11938477/115597728-93edb780-a2a7-11eb-9fe6-b78902700d18.png)

**Comment by LAlexMHllc** [comment]
NOTE: When Approved is checked, Risk Approach and Risk Approach Approver fields become disabled (see screenshots above). When the form is closed, then Edit risk again, both are enabled.

**Comment by curtismayer** [comment]
Design being changed which makes this issue irrelevant.
