### ISSUE TITLE
Risk approval updates and risk required fields

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mGis#2378]
Risk Approach approval can be simplified to a simple toggle (checkbox).  
When not yet approved (also approval is not required) it will just show the checkbox unchecked.

![image](https://user-images.githubusercontent.com/67476905/115607813-6dce1480-a2b3-11eb-9bff-02b97d8b1223.png)

When checked the site will capture and display the name of the approver and the date/time of the approval.

![image](https://user-images.githubusercontent.com/67476905/115608062-c30a2600-a2b3-11eb-99e2-caf4195b6ed8.png)

As for required fields of Risks, because entering a risk, prioritizing it, defining its controls, etc. are all different steps of risk management we should limit the required fields.  So the following fields are the only required fields to be able to save a Risk:

- Risk Name
- Risk Description
- Category
- Identified Date
- Probability (defaults to 1- Rare)
- Impact Level (defaults to 1 - Negligible)

**Comment by LAlexMHllc** [comment]
Risk Approach Due Date:
- Still has required
- Should not be able to select date before Identified Date

Screenshot Example

![risk_form_risk_approach_due_date_issues](https://user-images.githubusercontent.com/11938477/115734839-00c08a80-a358-11eb-8fa3-3a324c285d53.png)

**Comment by LAlexMHllc** [comment]
Risk Approach should not become disabled when Risk Approach Approver is checked.
Screenshot Example

![risk_form_risk_approach_disabled_when_approved_checked](https://user-images.githubusercontent.com/11938477/115736824-96a8e500-a359-11eb-8369-4a06fdbe62bc.png)

**Comment by LAlexMHllc** [comment]
Layout of the contents of Risk Approach Approved box should remain unchanged, since there is plenty of space.
Screenshot Example

![risk_approach_approver_layout](https://user-images.githubusercontent.com/11938477/115737569-41b99e80-a35a-11eb-942c-86f6a5bfcf61.png)

**Comment by LAlexMHllc** [comment]
Approved checked, Date/Time stamp, and Approver did not stick for saved risk.
Screenshot Example

![risk_form_approved_checked_date-time_approver_not_stick](https://user-images.githubusercontent.com/11938477/115739167-af19ff00-a35b-11eb-9c84-ed536fea8b34.png)

**Comment by juan-rivera-2020** [comment]
I observed that the failure to save the Risk Approval check and date/timestamp was only occurring in the QA environment (not locally).  Currently modifying code to correct this behavior.
