### ISSUE TITLE
Admin/Facilities screen: Deleted task should not display as option under Filter form for Tasks; and submit results should not display facility.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#241]
Task(s) no longer exist for facility, yet still included in filter form/results.

Screenshot Example

![deleted_tasks_still_remain_tasks_filter_options_and_resultsjpg](https://user-images.githubusercontent.com/11938477/81186625-04110980-8f81-11ea-970c-7e18c33c432d.jpg)

**Comment by bluenevus** [comment]
that field has to be a search term

the task type is a drop down

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8229 Boone Blvd, Suite 500  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________

**Comment by LAlexMHllc** [comment]
Deleted task should not display as Task filter search result
