### ISSUE TITLE
Project dashboard - Facility Summary modal: unable to select Due Date, even with admin role.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#242]
Screenshot Example

![facility_summary_modal_unable_select_due_date](https://user-images.githubusercontent.com/11938477/81194871-2740b680-8f8b-11ea-99a6-bf91a526a944.jpg)

**Comment by bluenevus** [comment]
This is  real show stopper

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by bluenevus** [comment]
I was able to enter it on one site.  after that one site, every other site had locked due date fields and couldn't be entered or modified

**Comment by bluenevus** [comment]
when the status is selected then you can pick a due date
