### ISSUE TITLE
Need default Program on startup to prevent error

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#2423]
If user does not select a preferred program in Profile page, mPATH default Map view will render blank project rollup screen on right with "Can't find facilityName" error in console.  With a default view already in place, this may also require a default program.  

![image](https://user-images.githubusercontent.com/72885316/116416351-42de4600-a808-11eb-9f12-4b6dbe86e8fe.png)

**Comment by LAlexMHllc** [comment]
See related Issue #2333

**Comment by juan-rivera-2020** [comment]
Fixed 29Apr21
