### ISSUE TITLE
need to notify users that the status must updated before you can enter a due date

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#248]

**Comment by bluenevus** [comment]
specifically on this screen you cannot click a date if you don't have a status however, the user doesn't know that is what they must do so we are looking for a pop up of sorts that tells them to first enter a status to then enter a date so they will know the workflow expected if they click the date before the status has been updated

![image](https://user-images.githubusercontent.com/3675043/81213243-15b7d880-8fa4-11ea-827c-d092fc59fd8a.png)

**Comment by LAlexMHllc** [comment]
At any time the Status="No Status", the Due date should be blank and should not accept input.

Screenshot Example

![facility_summary_modal_no_status_clear_due_date](https://user-images.githubusercontent.com/11938477/81214177-74318680-8fa5-11ea-8f90-2a6a1b9ce6f5.jpg)
