### ISSUE TITLE
Facility Summary - Issues tab: Include issue filters using enumerations

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#300]
Screenshot Example

![facility_summary_modal_issues_tab_include_issue_filters_1](https://user-images.githubusercontent.com/11938477/84193304-3b377680-aa69-11ea-80df-12a77d92b37f.png)

**Comment by bluenevus** [comment]
well, no issue status...that we can remove as that will be a percentage complete bar like tasks requested in other issues so we just need  Issue Type and Issue Severity filters
