### ISSUE TITLE
Admin/Tasks - Batch Action: Include "Add Task Selected"; when clicked display confirm form.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#306]
Add Task Selected - Form: Name (textbox), Project (drop-down select), Facilities (cascading multi-drop-down select to Project, with only Facilities assigned to project as options), Task Type (drop-down select), Start Date (textbox with datepicker), Due Date (textbox with datepicker), Progress (slider), Description (textarea), OK and Cancel buttons.

**Comment by bilel-kedidi** [comment]
i don't understand this ticket.
can you please develop

**Comment by LAlexMHllc** [comment]
The options for "Facilities" multi-dropdown select are dependent upon the "Project" selected. When the default option "Select Project" displays, then Facilities options are blank. When a project is selected, all the Facility Names of facilities assigned to the selected project will display as options for the multi-dropdown select.

Screenshot Example

![admin_task_batch_actions_add_task_selected_form_1](https://user-images.githubusercontent.com/11938477/84408930-c2f0c280-abda-11ea-841a-fbd11c8419b8.png)
![admin_task_batch_actions_add_task_selected_form_2](https://user-images.githubusercontent.com/11938477/84408935-c5531c80-abda-11ea-8b1c-eb6e8f9bae07.png)

**Comment by LAlexMHllc** [comment]
NOTE: Include Progress % checkbox/function; Checklist Items; and Upload File.
