### ISSUE TITLE
Edit User Profile: not able to edit Password and Password Confirm

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#309]
Screenshot Example

![edit_user_profile_not_able_edit_password_password_confirm](https://user-images.githubusercontent.com/11938477/83908438-225f5600-a735-11ea-8664-71ee4e0495b9.png)

**Comment by bluenevus** [comment]
Need to be able to enforce password complexity and length setup under admin

This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.


Frank Tucker
Chief Executive Officer, Executive Office
t: 855-294-3547
m: 571-327-1211
frank.tucker@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by bilel-kedidi** [comment]
(Same as issue-298, you need to click to enable password input)
