### ISSUE TITLE
Consolidate issue type and issue severity to one line similar to date start and end right below it

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#320]
Consolidate issue severity and issue status to one line similar to date start and end right below it

![image](https://user-images.githubusercontent.com/3675043/84182033-c445b200-aa57-11ea-9b8b-62dde0d14700.png)

**Comment by LAlexMHllc** [comment]
If it is ok that Issue Severity and Issue Progress % are on one line instead, then this can be closed.
