### ISSUE TITLE
Project dashboard - Project Summary - Task Types: Fix the calculation for % complete for each task type.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#331]
Screenshot Examples

![project_summary_task_types_complete_percentage](https://user-images.githubusercontent.com/11938477/84404176-815d1900-abd4-11ea-86fc-32ade1a32b16.png)

**Comment by bluenevus** [comment]
Specifically, the issue on task type calculation is that its currently counting the percentage of task types when it needs to calculate the percentage complete of that specific task type

So in the training task type, that should calculate the percentage complete vs percentage of the count of tasks



Frank Tucker
Chief Executive Officer, Executive Office
t: 855-294-3547
m: 571-327-1211
frank.tucker@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.
