### ISSUE TITLE
allow admin to set order of the droplist and how its displayed on summary reports for Issue Status

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#346]
under admin, the admin should be able to set the order of how this is displayed below. That order will be for not only the drop list, but the order of how report summaries are laid out

![image](https://user-images.githubusercontent.com/3675043/84917153-f628cb00-b08c-11ea-837f-5a42761c8747.png)

**Comment by LAlexMHllc** [comment]
Unless you have changed your mind, Issue Status is going to be "Progress (in %)" bar, and this screen is to be removed.

**Comment by bluenevus** [comment]
yep forgot.  closing as it simply needs to be removed
