### ISSUE TITLE
Project dashboard - collapsible tabs for Filter Map and Facility Summary: Blue color is hard to see due to background, so should change color for more contrast.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#368]
Try orange color

Screenshot Example

![collapsible_tabs_modal_map](https://user-images.githubusercontent.com/11938477/85576442-6b088180-b606-11ea-9e28-83e1497d8148.png)

**Comment by bluenevus** [comment]
Like orange

Sent from my Verizon, Samsung Galaxy smartphone


Frank Tucker
Chief Executive Officer, Executive Office
t: 855-294-3547
m: 571-327-1211
frank.tucker@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.
________________________________
