### ISSUE TITLE
Project dashboard - Facility Summary should only be displayed when a facility pushpin is clicked; otherwise, the Project Summary should display instead.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#376]
Screenshot Example

![project_summary_display_non_pushpin_clicked](https://user-images.githubusercontent.com/11938477/86014774-bfd53f00-b9ee-11ea-8280-641ef40efd38.png)

**Comment by LAlexMHllc** [comment]
When the Facility Summary is shown and the user clicks on another area on the map other than a facility pushpin, the Project Summary should display instead of the Facility Summary.

**Comment by bluenevus** [comment]
when you click a push pin, it opens the facility to edit.  when you click an area that is NOT a push pin, that facility should close and the report should show which it doesn't.  Right now you have to manually drag the facility form closed.  If you do that and click that facility again, the facility form doesn't reopen.  YOu have to drag it back open.  It will only open on its own when you click a different facility so the workflow is messed up.  You click a pin, the form opens...it should always work that way no matter what.  You click a different part of the map which is not a push pin, the form closes...always.  You click a different site push pin, the form opens to the overview for that new site.
