### ISSUE TITLE
increase max document upload size to 50mb

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#381]
having some real issues on document size being 7mb

Need it bigger, probably better if its configurable under settings

**Comment by bilel-kedidi** [comment]
https://www.tecmint.com/limit-file-upload-size-in-nginx/

**Comment by bluenevus** [comment]
I did that, there is somthing in the form that says its limited to 7mb and the form itself then gives you an error message that its too large
![image](https://user-images.githubusercontent.com/3675043/86395428-3af85880-bc6e-11ea-8ee0-097a994037a1.png)
