### ISSUE TITLE
based on issue 388 and 389, add a new filter button for my tasks and my issues

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#391]
![image](https://user-images.githubusercontent.com/3675043/86515362-57b79c00-bde6-11ea-94b3-81cccf75e060.png)

![image](https://user-images.githubusercontent.com/3675043/86515369-5d14e680-bde6-11ea-88b7-63db6d5ce31e.png)

This should filter only those tasks and checklist items the user is assigned.  That is, it only shows the task if the person has a checklist item assigned to them or the task itself is assigned to them.  However, will not show items in the checklist not assigned to them and of course if they have no checklist or no task, it just doesn't show under my tasks.

The same logic is for my issues.

**Comment by LAlexMHllc** [comment]
When checked, My Tasks and My Issues do not filter listing.

![my_tasks_my_issues_do_not_filter_listings](https://user-images.githubusercontent.com/11938477/91067529-09ae6000-e601-11ea-8e0d-0345b3eac718.png)
