### ISSUE TITLE
for issues under the admin menu, we need the facility and the and the project just like you did under task admin

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#394]
![image](https://user-images.githubusercontent.com/3675043/86517549-d23ce780-bdf7-11ea-899d-8b06cd5bddf6.png)

**Comment by LAlexMHllc** [comment]
Include the Facility and Project on filter form as well.

![admin_issues_filter_form](https://user-images.githubusercontent.com/11938477/87809524-88a5c100-c829-11ea-9fdb-0ee97ce6e76c.png)
