### ISSUE TITLE
Since saving a Note, Task, or Issue with a file attachment takes a while, when user clicks "Save", display uploading indicator. Also disable delete file icon, since entry will be saved with file anyway, or might error.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#398]
![save_with_file_attachment](https://user-images.githubusercontent.com/11938477/86603394-f02e5780-bf71-11ea-8f18-3ba36959d140.png)

**Comment by bluenevus** [comment]
I think an indicator is a good idea that its working.

I don't  understand this " Also disable delete file icon, since entry will be saved with file anyway, or might error. "  It seems to work right now

**Comment by LAlexMHllc** [comment]
I clicked the delete attachment icon, then clicked OK to confirm delete. File attachment was removed, but saved. File was approx 8mb. Not sure if the file is approx 50mb if it will save, or might error.

**Comment by LAlexMHllc** [comment]
If the "saving indicator" will not display the form while updating, then dismiss.
