### ISSUE TITLE
Project dashboard - Project Summary - Tasks section: Include link "View All Tasks" (with permission). When clicked, display "All Tasks" modal.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#406]
"All Tasks" modal will display overall task list that shows who is responsible for each, etc.
Filter by Facility Name, Filter by Facility Group, Filter by Task Type, Filter by User Email

Screenshot Example

![view_all_tasks_link_display_all_tasks_modal](https://user-images.githubusercontent.com/11938477/86633964-4ebdfa80-bf9f-11ea-8c30-f060f8b8d753.png)

**Comment by bluenevus** [comment]
I really don't want another link by you can  hyperlink the design, develop & test to pop up a list of tasks that fit that criteria and facility.
