### ISSUE TITLE
Project dashboard - Project Summary -Issues section: Include link "View All Issues" (with permission). When clicked, display "All Issues" modal.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#407]
"All Issues" modal will display overall issues list.
Filter by Facility Name, Filter by Facility Group, Filter by Issue Type, Filter by Issue Severity

Screenshot Example

![view_all_issues_link_display_all_issues_modal](https://user-images.githubusercontent.com/11938477/86634599-0e12b100-bfa0-11ea-8f87-0c1e2af4cdb2.png)

**Comment by bluenevus** [comment]
I really don't want another link by you can  hyperlink  touchwork to pop up a list of tasks issues fit that criteria and facility.
