### ISSUE TITLE
Admin/Users - Privileges section: Notes should either have both Write and Delete checked/unchecked automatically.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#424]
Screenshot Example

![admin_user_privileges_Notes_write_delete_both_checked_or_unchecked](https://user-images.githubusercontent.com/11938477/87322292-3d26a680-c4fb-11ea-95b6-fbd67afbdf8e.png)

**Comment by bluenevus** [comment]
we will leave it for now
