### ISSUE TITLE
Admin/Faciliites - Should Table display AND Batch Actions - Assign Due Date and Status Selected be changed to these alternatives to avoid issues when facilities assigned to project have different Statuses and/or Due Dates?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#428]
Remove "Projects" column and include Project section for each entry to include Project Name, Status, and Due Date.

Screenshot Example of Table display

![admin_facilities_alt_table_with_projects_section](https://user-images.githubusercontent.com/11938477/88310320-8508b300-ccdd-11ea-9bec-8000bdacc742.png)

Change to Batch Actions - Assign Due Date And/Or Status Selected

Screenshot Example

![admin_facilities_batch_actions_assign_due_date_and_or_status_selected](https://user-images.githubusercontent.com/11938477/88310631-e3ce2c80-ccdd-11ea-9a59-9cd304d83ae8.png)

**Comment by bluenevus** [comment]
if the users ask it, we will put it as a requirement.  check with david
