### ISSUE TITLE
Admin/Facilities - Batch Actions - Assign Due Date and Status Selected: Can default project selected be the filtered project?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#429]
Screenshot Example of filter with project selected

![admin_facilities_project_filter](https://user-images.githubusercontent.com/11938477/87328583-b4603880-c503-11ea-963c-3d362a8ac8ef.png)

The form displays with the first option selected by default on the drop-down select.
Can default project selected be the filtered project so user will not have to select Project?

![admin_facilities_batch_actions_due_date_when_already_different](https://user-images.githubusercontent.com/11938477/87325859-fd15f280-c4ff-11ea-94bd-6ab521c1b350.png)

**Comment by bluenevus** [comment]
if the users ask it, we will put it as a requirement.  check with david
