### ISSUE TITLE
add a tab in this filter view that says "Favorites"

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#433]
This will give the users the ability to "Save" their filter, give it a name and it show up in the "Favorites" tab.  The filter will be in a "Filters" tab.  There will be a new button at the bottom of the filter list called "Save to Favorites".  When clicked, it will allow them to give that filter a name.  Once named, they can click save and it will show up on their favorites tab.  They can Edit the name of their favorites or delete the favorite link they saved in the favorites tab.  If they have admin privileges, they can "Share" these favorites with all.  This will be in a 3rd tab called "Shared".  Only admins can have the option to save to favorites as a shared link in the Shared tab.  Only admins can edit or delete shared saved filters under the Shared Tab.  The shared tab is visible to all users with read only privileges along with Favorites.

![image](https://user-images.githubusercontent.com/3675043/87359455-d4105480-c535-11ea-94d1-88bf3ab2006f.png)

**Comment by LAlexMHllc** [comment]
Closing, since Favorites included on Advanced Filters.
NOTE: See issues opened related to Favorites.
