### ISSUE TITLE
After Issue #388 and #394 fixed, on admin/issues screen, include "Assigned To" on table, edit issue form, and Filters form

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#452]

**Comment by bluenevus** [comment]
need more info on this

**Comment by LAlexMHllc** [comment]
Screenshot Example of Assigned To on admin/issues table

![admin_issues_table_assigned_to](https://user-images.githubusercontent.com/11938477/88301309-7668ce80-ccd2-11ea-9549-bffb1983a508.png)

Screenshot Example of Assigned To on admin/issues filter form

![admin_issues_filter_assigned_to](https://user-images.githubusercontent.com/11938477/88302344-bc726200-ccd3-11ea-8175-74494ca99946.png)
