### ISSUE TITLE
Admin/User forms - Centrally locate Password Strength and remove from user forms on the Password Generator section. Same rules should apply to all users.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#465]
Screenshot Example

![password_generator_each_user](https://user-images.githubusercontent.com/11938477/88568249-abdd2700-d006-11ea-8c04-8cd44a4c854c.png)

**Comment by LAlexMHllc** [comment]
Should this be moved under Settings?

**Comment by bluenevus** [comment]
centrally managed, applied to all passwords

**Comment by LAlexMHllc** [comment]
Still missing from admin/settings

**Comment by LAlexMHllc** [comment]
Not able to adjust Password Settings because all form elements are disabled and readonly

Screenshot Example

![admin_settings_password_generator_disabled_readonly](https://user-images.githubusercontent.com/11938477/97024114-6e643900-1524-11eb-94bd-687ad0b1b0cf.png)
