### ISSUE TITLE
"Export" function for Filter View should include options: Excel (default radio button); PDF; and MS Project

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#473]
Export Gantt to PDF and Excel

**Comment by bluenevus** [comment]
Excel is the most important.  Very important

**Comment by bluenevus** [comment]
I mean, if there is an export to microsoft project that would be even better

**Comment by LAlexMHllc** [comment]
When "export" link on Filter View form is clicked, export the file in the checked radio button format.

**Comment by bluenevus** [comment]
this will be resolved by changing libraries as requested here https://github.com/MicroHealthLLC/mGis/issues/650
