### ISSUE TITLE
Unable to delete user - ActiveRecord: StatementInvalid error screen displays

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#475]
Screenshot of error screen when user was already removed from projects and all privileges removed (even default)

![admin_user_unable_to_delete_due_to_privileges](https://user-images.githubusercontent.com/11938477/89058752-e3611180-d32d-11ea-96da-51aac6efea00.png)

**Comment by bluenevus** [comment]
and we can't have error messages like this.  we need to provide something more insightful on the issue so they can ask their system administrator for help
