### ISSUE TITLE
Not able to include user on project

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#5]

**Comment by bluenevus** [comment]
We need better descriptions on this.  Screenshots and it really explained on what we expect it to do…not just say we can’t do x y z

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
New Project and Edit Project forms unable to select user to assign to project.

Screenshot Example

![new_project_edit_project_cannot_select_users_to_assign](https://user-images.githubusercontent.com/11938477/73883448-f6d56900-4831-11ea-98f5-a0386f0f14b8.jpg)
 to assign to project.

**Comment by LAlexMHllc** [comment]
Edit User form unable to select project to assign user to.

Screenshot Example

![edit_user_unable_to_select_project_to_assign_user](https://user-images.githubusercontent.com/11938477/73883657-53d11f00-4832-11ea-9deb-a7d1d051bb54.jpg)
