### ISSUE TITLE
Project screen - Facility Summary: disable SAVE button when checklist item assigned user was removed as an Task/Issue Assigned User; and when there are no Task/Issue Assigned Users, then all Checklist Assigned Users should be blank.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#510]
User previously selected as Task/Issue Assigned User, then Checklist Item Assigned User. Then user was removed as Task/Issue Assigned User, but remained selected as Checklist Item Assigned User. 
When the Save button was clicked on the Add Task form, the task was not saved.
When the Save button was clicked on Edit Task form, the task updated.

Screenshot Example

![should_not_be_able_save_assigned_user_checklist_after_removed_assigned_task_user](https://user-images.githubusercontent.com/11938477/90537963-e5a7d600-e14b-11ea-91e7-4f5f37fdaa89.png)

**Comment by bluenevus** [comment]
too many rules...not sure if this is needed.  I don't want a bunch of rules unless its an issue
