### ISSUE TITLE
the checklist item assignment isn't searching the list of users

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#512]
see below.  Its blank and remains blank when I search for known users in the system

![image](https://user-images.githubusercontent.com/3675043/90545703-0aee1180-e157-11ea-92fe-fd027c7c3d85.png)

**Comment by LAlexMHllc** [comment]
Have to assign users to task first, then assign checklist users

**Comment by bluenevus** [comment]
I don't think its important about sequence here.  that isn't what is important today.  What is important is the ability to search for a user in the system and pick them

**Comment by bluenevus** [comment]
nevermind yes, apparently you Have to assign users to task first, then assign checklist users.  its not very intuitive
