### ISSUE TITLE
Project Screen - Facility Summary: Indicate with an Alert when Task/Issue Assigned User delete is clicked when there is a matching Checklist Assigned To user.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#513]
Screenshot Example

![alert_delete_task_or_issue_assigned_user_when_matching_checklist_assigned_to_exist](https://user-images.githubusercontent.com/11938477/90668302-e315b100-e21d-11ea-8247-55c2e4a5fae3.png)

**Comment by bluenevus** [comment]
its ok for the alert on a delete as that is common but we don't want an alert because a checklist and the overall task has matching names.  that will get overwhelming for users because it happens all the time
