### ISSUE TITLE
Project screen - Facility Summary: Should always be able to remove Checklist Assigned To user.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#514]
Presently, after user removed as Task/Issue Assigned User and user still exist as Checklist Assigned To user, not able to remove Assigned To user. 
Screenshot Example
![assigned_users_removed_can_not_remove_checklist_assigned](https://user-images.githubusercontent.com/11938477/90673006-0c860b00-e225-11ea-80de-49a8c9207b4a.png)

Should always be able to remove Checklist Assigned To user.
Screenshot Example
![need_to_be_able_to_always_remove_checklist_assigned_to](https://user-images.githubusercontent.com/11938477/90673435-bebdd280-e225-11ea-93b4-0924ec5f16d8.png)

**Comment by bluenevus** [comment]
We should be able to add users to checklists without the user being assigned to the entire task above.  We should be able to assign a user even if they haven't assign the entire task above.  We just need to be able to assign users of the system the task or checklist
