### ISSUE TITLE
Project screen - Filter View: Change all % Progress Range filters to input textboxes for Min. % and Max. %. For validation allow integer values 0 through 100.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#541]
% Range picker should be similar to datepicker.

Screenshot Example

![filter_view_percentage_range_filters_start_and_end_pickers](https://user-images.githubusercontent.com/11938477/91486816-ceb76100-e87a-11ea-9fba-4dddd376e5ff.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![filter_view_percentage_min_max_values](https://user-images.githubusercontent.com/11938477/91752679-b6a25300-eb94-11ea-9149-25c6986a2bbd.png)

**Comment by LAlexMHllc** [comment]
When Min = blank AND Max = blank, include ranges 0 through 100.
When Min <> blank AND Max = blank, include ranges from Min through 100.
When Min = blank AND Max <> blank, include ranges from 0 through Max.

NOTE: Since the view updates with each input, % Progress Range could error when Min > Max OR Max < Min.
Therefore, when Min and Max <> blank AND:
- User inputs Min > existing Max, automatically update Max = blank.
- User inputs Max < existing Min, automatically update Min = blank.

**Comment by bluenevus** [comment]
if one of the fields are blank or the max isn't greater than the min then put an error message alerting Both fields need to be filled and the Max has to be greater than the min

**Comment by bluenevus** [comment]
don't actually put these words above the number form "
![image](https://user-images.githubusercontent.com/3675043/91867034-29690800-ec41-11ea-82ac-ac726c95832d.png)"

**Comment by LAlexMHllc** [comment]
NOTE: Validate input and display error when input not valid.
