### ISSUE TITLE
Project screen - Include an "On Watch View": A Sr Management Report view and pdf export.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#543]
![high_level_report_explanation_r1](https://user-images.githubusercontent.com/11938477/92246063-3c731680-ee93-11ea-8e2f-a8de497156af.png)

If checkbox is selected, the task title will be visible on the Timeline, marked at the due date. 

Example: Add checkbox for selecting "executive interest task"​

![checkmark_example](https://user-images.githubusercontent.com/11938477/92148182-2cebc300-edea-11ea-815a-01854981496c.png)

On Watch View Example
![on_watch_example_top](https://user-images.githubusercontent.com/11938477/93095082-ac8e5300-f670-11ea-8c75-b948bb65580c.png)
![on_watch_example_bottom](https://user-images.githubusercontent.com/11938477/93095158-c2037d00-f670-11ea-9678-7acc18b9d240.png)

**Comment by bluenevus** [comment]
Can we call it Milestone Progression instead of control gates so its more generic for other users?

**Comment by bluenevus** [comment]
put it in a new tab called "Timeline"

**Comment by bluenevus** [comment]
we need to add the same for issues so below list of tasks, same with issues and had a check box to put an issue on watch and those will show up in this view and timeline also

**Comment by bluenevus** [comment]
we need to redesign the layout of "On Watch" as its not printer friendly with the map.  depending on how mayn tasks and issues they mark, it will be a problem.  we will need to spend some time designing the report layout with the timeline, watched tasks, watched issues and milestone progression in a dashboard before its built

**Comment by LAlexMHllc** [comment]
NOTE: For Watched Tasks and Watched Issues listing on the right sidebar, include the Facility Name and Facility Group for each listing.
