### ISSUE TITLE
Project screen - Project Summary: Task Complete and Incomplete totals are incorrect.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#555]
Screenshot Example

![project_summary_task_complete_incomplete_counts_are_off_by_1](https://user-images.githubusercontent.com/11938477/93224234-e594f900-f73e-11ea-8a1b-36e522e3e1d5.png)

**Comment by bluenevus** [comment]
also, all the ones with 0 tasks should not display.  only task types with a task

**Comment by LAlexMHllc** [comment]
See related Issue #553
