### ISSUE TITLE
Project screen - Clicking "export" on Filter View when On Watch View is displayed did not download a file; just changed text color.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#565]
Screenshot Example

![clicking_export_watch_view_does_nothing_but_change_text_color](https://user-images.githubusercontent.com/11938477/94036632-82d0dc80-fd92-11ea-8bce-4d42498abab9.png)

**Comment by bluenevus** [comment]
the intent is a printable report in pdf
