### ISSUE TITLE
Project screen - On Watch View: Watched Issue Stats: Change text "Milestone Progressions" to "Watched Issues vs Total"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#571]
Screenshot Example

![on_watch_view_change_watched_issue_stats_milestone_progression_text](https://user-images.githubusercontent.com/11938477/94195681-521ba080-fe81-11ea-84bf-f1d22a2a29e9.png)

**Comment by bluenevus** [comment]
instead of the wording above say "Watched Issues vs Total"

**Comment by bluenevus** [comment]
This is specifically for the Issue section
