### ISSUE TITLE
Project screen - On Watch View: Watched Stats - Assigned Users with Totals for Tasks/Issues including Checklist Items charts

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#572]
Change the Assigned Users chart for Tasks/Checklist Items to only include users assigned to a task/checklist item.

Change the Assigned Users chart for Issues/Checklist Items to only include users assigned to a issue/checklist item.

Screenshot Example

![on_watch_view_watched_stats_assigned_users_1](https://user-images.githubusercontent.com/11938477/94044935-cb8d9300-fd9c-11ea-902d-15200c5e880f.png)

![on_watch_view_watched_stats_assigned_users_2](https://user-images.githubusercontent.com/11938477/94058968-c554e200-fdaf-11ea-9d78-95487f4ac7d5.png)

**Comment by LAlexMHllc** [comment]
If possible, can the assigned users with their total bars scroll?

Screenshot Example

![assigned_users_with_vertical_scroll](https://user-images.githubusercontent.com/11938477/94052142-853d3180-fda6-11ea-9ce5-d011fb77cb3b.png)

**Comment by bluenevus** [comment]
this is what it looks like when there are many names

![image](https://user-images.githubusercontent.com/3675043/94193236-1af7c000-fe7e-11ea-85c1-daff92e1c64f.png)

**Comment by bluenevus** [comment]
also, it shouldn't include names of people who are not assigned tasks or are not assigned to the project.  Right now, it lists all users
