### ISSUE TITLE
the watchboard shows no progress on the issue but the actual issue does have progress

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#587]
![image](https://user-images.githubusercontent.com/3675043/94218182-d423bd80-feb1-11ea-821d-45784766d02d.png)

![image](https://user-images.githubusercontent.com/3675043/94218194-e1d94300-feb1-11ea-9515-6a9c7ef22e07.png)

so it should have shown that its 50% complete on the watchboard

**Comment by LAlexMHllc** [comment]
Change header text from "Watched Issues Completion" to "Watched Issues Progress" and edit calculation.

Screenshot Example

![change_watched_issues_completion_to_watched_issues_progress_edit_calculation](https://user-images.githubusercontent.com/11938477/94278432-cce3ca80-ff18-11ea-928a-0b4369b0ba64.png)

**Comment by bluenevus** [comment]
Watched Issue Progress

Not Issues with an s
