### ISSUE TITLE
Project screen - On Watch View: Change text "Watched Task Completion" to "Watched Task Progress" and edit calculation.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#588]
Screenshot Example

![change_watched_task_completion_to_watched_task_progress_edit_calculation](https://user-images.githubusercontent.com/11938477/94279351-f5b88f80-ff19-11ea-8668-65c0e36a9ea1.png)

**Comment by bluenevus** [comment]
Watched Task Progress

not TASKS
