### ISSUE TITLE
admin/users - Create User and Edit User: Password Generator does not meet the requirement restrictions. Should be the same as Password under Profile.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#617]
Must be at least 12 characters and contain at least: 1 uppercase letter, 1 lowercase letter, and 1 special character

Screenshot Example of admin/users form Password Generator section

![create_edit_user__password_generator_does_not_meet_requirement_restrictions](https://user-images.githubusercontent.com/11938477/96604605-4aee8380-12c3-11eb-935f-d4cd2029d5a9.png)

Screenshot Example of Profile Password

![profile_password](https://user-images.githubusercontent.com/11938477/96609252-509a9800-12c8-11eb-805c-d49d2f1ecd52.png)

**Comment by bluenevus** [comment]
this appears linked to https://github.com/MicroHealthLLC/mGis/issues/668

**Comment by LAlexMHllc** [comment]
Reopened since User Generated Password does not always meet the restrictions requirement set under Settings.

Screenshot Example

![password_generator_not_following_restrictions_requirement](https://user-images.githubusercontent.com/11938477/97482041-0353a180-192c-11eb-8b10-090c75ae5105.png)
