### ISSUE TITLE
Confirm when "Remove" clicked for checklist item on Task and Issue forms

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#625]
Screenshot Example

![admin_tasks_forms_admin_issues_forms_confirm_remove_checklist_item](https://user-images.githubusercontent.com/11938477/96626675-cceba600-12dd-11eb-9800-1759e19559c7.png)

**Comment by juan-rivera-2020** [comment]
Please confirm desired functionality: User clicks "Remove" and will be prompted with a window/modal prompting the user to confirm "Remove"?

**Comment by LAlexMHllc** [comment]
yes

**Comment by LAlexMHllc** [comment]
User clicked "Remove" and confirm displays.

Screenshot Example

![confirm_delete_checklist_item](https://user-images.githubusercontent.com/11938477/97218317-e9388880-179e-11eb-9f46-ace47ac79c3b.png)

**Comment by juan-rivera-2020** [comment]
The 'Delete' checkbox already provides the confirmation/prompt action.  Should we just change the label of the 'Remove' button to 'Cancel' or 'Close'.  Currently, the Remove button just cancels their current entry.  It doesn't delete previously stored data.  
![image](https://user-images.githubusercontent.com/72885316/99453708-5bf6d880-28f3-11eb-8190-c6ca9134ef5f.png)
