### ISSUE TITLE
if there is a related issue or task, display it on this view

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#626]
![image](https://user-images.githubusercontent.com/3675043/96659363-c62c5580-1314-11eb-9ecc-c5830a59934e.png)

**Comment by LAlexMHllc** [comment]
YES, Related Tasks and Related Issues are on the Edit Watched Task and Edit Watched Issue forms

Screenshot Example

![on_watch_view_forms_related_issues_related_tasks](https://user-images.githubusercontent.com/11938477/97038509-efc5c680-1538-11eb-8ab0-25cc34797a6f.png)
