### ISSUE TITLE
in dev, related issues and task shows up in prod it does not

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#628]
in dev, there was no issues compiling.  however, in prod there were issues compiling.  It took a long time then said failed.  then when I told it to precompile again it says everything up to date however, some of the new features just doesn't show in this case, the related issues and task shows in dev after precompile but it won't in production mode

![image](https://user-images.githubusercontent.com/3675043/96661326-caa73d00-1319-11eb-8df6-348bb6396b6f.png)

**Comment by bluenevus** [comment]
cleared the tmp cache and this is the error
![image](https://user-images.githubusercontent.com/3675043/96661677-a6982b80-131a-11eb-816e-aa1be155e1ac.png)

**Comment by bluenevus** [comment]
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by bluenevus** [comment]
So I tried rake tmp:cache:clear and removed package-lock.json so I can build fresh packages in yarn and do a new clean precompile.  Same issue as the image above

**Comment by bluenevus** [comment]
like I said, no issues in development mode...features show up.  however in production mode, features don't show up and the error above

**Comment by LAlexMHllc** [comment]
Updates not pulled to prod yet
