### ISSUE TITLE
admin/users - User form: can not view/copy password

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#632]
Screenshot Example

![admin_user_forms_not_able_to_copy_password](https://user-images.githubusercontent.com/11938477/96751589-6200a480-139b-11eb-9d14-6aecedebb7e1.png)

**Comment by juan-rivera-2020** [comment]
Please test.

Changed HTML <input type="password"> to <input type="text">.  This type change also enabled the “Copy Password” function and now renders viewable (alphanumeric) characters.

This fix will require the password generator to also output special characters.  Working that issue now.
