### ISSUE TITLE
Remove blocked dates from all datepickers

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#637]
Start Date, Due Date, Expected Completion Date for Tasks, Issues, and Facility Project due date. On both the Client Panel and Admin Panel

Screenshot Example

![datepicker_no_nonselectable_dates](https://user-images.githubusercontent.com/11938477/97033775-dc632d00-1531-11eb-8518-48f32a468f6e.png)

**Comment by JuanCodeAtATime** [comment]
Fixed in Client Task and Issues datepickers.  Working on gantt view datepicker.
