### ISSUE TITLE
Include Washington, DC, Puerto Rico, Virgin Islands, Guam, Philippines Island, and American Samoa for multi-dropdown select options for Facility Groups forms.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#66]

**Comment by bluenevus** [comment]
Facility groups are enumerations.  You add the groups there and assign it to a facility

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LAlexMHllc** [comment]
Add Facility Group form and Edit Facility Group form have "States". Would you like this form element to be removed?

**Comment by bluenevus** [comment]
No states at all

 

Facility group is just the enumeration

 

--- vr, Frank
