### ISSUE TITLE
Project screen - Since related task/issue is not reciprocal, user has no way of seeing the relations. When user tries to delete related task/issue, it will not delete nor give warning.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#660]
Screenshot Example

![not_reciprocal_related_task_issue_1](https://user-images.githubusercontent.com/11938477/97193900-e67a6b00-177f-11eb-9de5-530e071278ce.png)

![not_reciprocal_related_task_issue_2](https://user-images.githubusercontent.com/11938477/97193912-ea0df200-177f-11eb-9086-12ae137fa860.png)

**Comment by bluenevus** [comment]
you can't delete at all even when you remove the link to the task or issues if it was linked before

![image](https://user-images.githubusercontent.com/3675043/97632765-5e0efb00-1a09-11eb-87da-88c224fd8e8c.png)

**Comment by bluenevus** [comment]
the bigger issue is you can't delete any task or issue that is related or was related to another task or issue.  meaning if there was a related issue before and it was then removed.  you still can't delete the task.  really a delete simply should delete the task and relationships without the user having to remove them individually

**Comment by bluenevus** [comment]
this was fixed.
