### ISSUE TITLE
Filter View: Should include "Search By Task Checklist Users" and "Search By Issue Checklist Users"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#662]
Screenshot Example

![filter_view_include_search_checklist_users_task_and_issue](https://user-images.githubusercontent.com/11938477/97198547-4fb0ad00-1785-11eb-9157-22c7112ef779.png)

Filters users assigned to Task Checklist Item and Issue Checklist Item

Screenshot Example

![assigned_user_for_task_or_issue_checklist_item](https://user-images.githubusercontent.com/11938477/97216258-f142f900-179b-11eb-9dd5-ecd48256a195.png)

**Comment by bluenevus** [comment]
really search by user means it should filter to anything assigned to that user inclusive in one search box NOT a bunch of different ones

**Comment by bluenevus** [comment]
please
