### ISSUE TITLE
"Members" tab still not showing in the client panel even when permissions are given

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#667]
![image](https://user-images.githubusercontent.com/3675043/97225504-20139c00-17a9-11eb-95a9-4fca80baf9c0.png)

**Comment by bluenevus** [comment]
the tab should display after documents tab

**Comment by juan-rivera-2020** [comment]
MembersView component imported but the file with that component is not in the master repo.

Reference:  "import MembersView from './../components/dashboard/members_view'"  

Bilel notified.
