### ISSUE TITLE
admin/users - New User form: User should be able to view password characters; password should have same restrictions as Profile password; user should be able to copy.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#668]
Screenshot Example

![admin_user_forms_password_viewable_meet_restrictions_copy](https://user-images.githubusercontent.com/11938477/97314670-518a7700-183e-11eb-95f1-71beae8256c3.png)

**Comment by bluenevus** [comment]
this appears linked to https://github.com/MicroHealthLLC/mGis/issues/617
