### ISSUE TITLE
Project screen - Facility Groups modal - Facilities modal: Fix initial position of Edit Task modal and Edit Issue modal.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#684]
Screenshot Example

![i_facility_groups_modal_click_edit_task_1](https://user-images.githubusercontent.com/11938477/97343227-9e317a80-185d-11eb-8048-a574d1cfbed8.png)

![i_facility_groups_modal_click_edit_task_2](https://user-images.githubusercontent.com/11938477/97343243-a25d9800-185d-11eb-82b1-5abacb76e43a.png)

**Comment by bluenevus** [comment]
we are going to delete this
