### ISSUE TITLE
Facility View - Default display should have: the first facility selected on the left pane; Facility Summary - Tasks tab displayed in the middle; and when an Active task exists, then Edit Task displayed for the first active task.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#700]
Screenshot Example

![facility_view_default_screen_display_tasks_tab_edit_first_active_task_open_when_exists](https://user-images.githubusercontent.com/11938477/97477717-5a567800-1926-11eb-85c0-6977e59ca6d5.png)

**Comment by bluenevus** [comment]
not sure about this yet
