### ISSUE TITLE
Project screen - Map View - Facility Summary - Issues tab: Edit icon clicked for issue; Edit Issue modal displayed in the center of the screen instead of the Facility Summary panel (as it did before).

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#702]
Screenshot Example

![facility_summary_edit_issue_clicked_1](https://user-images.githubusercontent.com/11938477/97479058-2e3bf680-1928-11eb-951a-532fbb5cbb6a.png)

![facility_summary_edit_issue_clicked_2](https://user-images.githubusercontent.com/11938477/97479068-32681400-1928-11eb-975d-7f8c9f68b7cd.png)

**Comment by LAlexMHllc** [comment]
Meant to close Issue #684

**Comment by bluenevus** [comment]
works as designed
