### ISSUE TITLE
need the ability to drag and drop to reorder checklists

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#712]
![image](https://user-images.githubusercontent.com/3675043/97572954-69d5cf80-19bf-11eb-821d-1f2cf2d8fdc9.png)

**Comment by LAlexMHllc** [comment]
Presently, only functioning on Client Panel - Tasks.
Not done for Client Panel - Issues.
Not done on Admin Panel.

**Comment by bluenevus** [comment]
so priority is on client panel issues

I don't care about the admin panel.  the purpose of the admin panel is bulk load information NOT to manage individual tasks.  Its for administration function ONLY...not to manage tasks like they do in the client panel
