### ISSUE TITLE
if my task is selected then you click a task from the my task list the page hangs

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#715]
![image](https://user-images.githubusercontent.com/3675043/97574908-4bbd9e80-19c2-11eb-8fa3-9faadb5c7263.png)

**Comment by bluenevus** [comment]
I did not click add task.  simply selected the task to edit

**Comment by bluenevus** [comment]
in map view also 
![image](https://user-images.githubusercontent.com/3675043/97575603-5dec0c80-19c3-11eb-9fb9-b48129aeabaa.png)

**Comment by LAlexMHllc** [comment]
Duplicate for Issue #619

**Comment by bluenevus** [comment]
the problem still exists.  if there are more than one task and you navigate to the 2nd task, it doesnt change the task in the right pane.  if you navigate back to the first task click the back button then click the 2nd task you get the same issue

![image](https://user-images.githubusercontent.com/3675043/98116133-dea08200-1e75-11eb-9a21-0492e34ef6cf.png)

**Comment by bluenevus** [comment]
I just tested it in our testing.  added 2 tasks and assigned them to me.  then filtered my task.  then clicked the first task and moved to the 2nd task and it did not change tasks however, it did not hang like production hangs.  It just doesn't change the right panel content.  then clicked add new task and still didn't change to a blank add form.  once again,  only when my task is checked
