### ISSUE TITLE
need new tab after issues tab called risk

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#719]
![image](https://user-images.githubusercontent.com/3675043/97576920-1e262480-19c5-11eb-917e-b3cfe1e03e5e.png)

Risk field includes
Risk Name: text
Risk Description: free text
Impact Description: free text
Task Category (enumeration)
Start Date and due date
Risk Owner (user selects from those assigned to the project)

Progress bar with auto calculate based on risk approach checklist below

Probability (5 highest) (enumeration 1-5)
Impact Level (5 highest)  (enumeration 1-5)
Priority level (this is auto calculated field of Impact * probability and color coded based on the risk matrix legend)
Risk Approach (enumeration Avoid, Mitigate, Transfer, Accept)
Risk Approach Description: free text
Risk Approach Checklist: checklist like task and issue

Files

Related Tasks:
Related issues:
Related Risks:  since this is a new relationship, we need to add this to task and issues so they can add relationships

display risk matrix as legend at the bottom and color code the priority level to match the matrix.  we won't be calling it consequence as its called Impact

we also need the plain language description next to the numbers like so in the enumeration and the heatmap so its plain as day to users

for example 1-Neglible, 2-Minor for Impact level enumeration
and 1-Rare, 2-Unlikely for probability enumeration

![image](https://user-images.githubusercontent.com/3675043/103229616-6bf5d500-4901-11eb-81b1-7e9721d1ad23.png)

This will need to behave like task and issues on the facility view, map view and on watch.  all enumerations will need to be filterable on the filter handle e

like task and issues, need the filter for task category, active, completed, all and my tasks. also priority, risk approach (not probability or impact on the screen)

On watch will need to be updated to display the stats on risks the same way task and issues are done

Facility overview will need a new section called Risks of complete, incomplete and overdue and like issues, display priority level like you do in issue types.  Gray = Very Low, Green = Low, Yellow = Medium, Orange = High and Red = Very High
so what we want to do is color code the text so they can see Very Low in gray and Low in green making it obvious

**Comment by LAlexMHllc** [comment]
Include Checklist items and Updates notes

**Comment by LAlexMHllc** [comment]
Moving to Work for this release since Risks tab is disabled for this release.
