### ISSUE TITLE
admin/users - Edit User form, Organization select text: "Please select organization" should be a placeholder for "blank", since Organization is not required.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#729]
Once an organization is saved for user, blank is no longer is an option.

Screenshot Example

![admin_user_forms_organization_please_select](https://user-images.githubusercontent.com/11938477/97588882-516fb000-19d3-11eb-9f79-7ead0fe50025.png)

**Comment by bluenevus** [comment]
they can unassign.  I dont' know the use case but I don't want to add rules and end up in the situation like the date blocked.  lets figure out if there is an issue before we create rules that funnel users into a specific workflow

**Comment by juan-rivera-2020** [comment]
Since the Organization dropdown is a reusable component, the same placeholder is used throughout the Admin Panel.  We can add in parenthesis something like this :

-Please select organization (optional)
-Please select organization (if applicable)

**Comment by LAlexMHllc** [comment]
For Edit User form, would like to be able to deselect an organization and leave it blank. Since organization is not required, blank should be an option (placeholder: Please select organization).

Screenshot Example where user had organization selected previously, but now can not deselect.

![admin_users_edit_user_deselect_organization_and_leave_blank](https://user-images.githubusercontent.com/11938477/98583295-236f5300-2292-11eb-9b1f-9999ad578510.png)
