### ISSUE TITLE
save will save what you have done but will not show it until the screen is manually refreshed for task and issues

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#755]
save will save what you have done but will not show it until the screen is manually refreshed.  that is, if you save then move to another issue.  then go back to see it.  you don't see any of the changes on screen.  however, if you manually refresh or move to another tab and return where that page reloads, then you will see the change you did

**Comment by LAlexMHllc** [comment]
See related Issue #727
