### ISSUE TITLE
admin/projects - Allow user to set enumeration settings per project, under the Advanced tab.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#761]
Screenshot Example

![admin_project_forms_advanced_tab_select_enumerations_0](https://user-images.githubusercontent.com/11938477/97887276-ae32d980-1cf7-11eb-8a94-3e648da42f0f.png)
![admin_project_forms_advanced_tab_select_enumerations_1](https://user-images.githubusercontent.com/11938477/97887285-b1c66080-1cf7-11eb-9d70-f67c7d730a63.png)
![admin_project_forms_advanced_tab_select_enumerations_2](https://user-images.githubusercontent.com/11938477/97887290-b428ba80-1cf7-11eb-9bbf-786793310c47.png)

**Comment by bluenevus** [comment]
I'm not sure if this is the workflow or that it should look like this at all.  Right now every project inherits the same enumerations.  There is the same user base, the facilities are the same but I need to be able to set enumeration settings per project.  This way milestones can be different per project.  Issue types can be different per project pretty much any enumeration can be set per project under admin

**Comment by bluenevus** [comment]
more like the new project and project edit screen should have all the enumerations to set there in tabs so you can reuse the pages you already created for the overall system

**Comment by LAlexMHllc** [comment]
The multi-select on the left starts off with ALL enumeration options. 
To include an option in the project, the user selects one or more options from the left, then clicks the arrow right to move the options to the list on the right.
To remove an option from the Project, the user selects the option from the right, then clicks the arrow left.

**Comment by bluenevus** [comment]
no I'm not sure it has to look like this we just need to be able to assign enumerations to projects and allow each project their own enumeration.  How you design that is up to you
