### ISSUE TITLE
When a user does not have Read privilege for On Watch View, the "on watch" checkbox should not display for Tasks and Issues listings.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#771]
Screenshot Example

![on_watch_checkbox_not_display_without_Read_privilege_On_Watch_View](https://user-images.githubusercontent.com/11938477/97917719-e7cd0a00-1d22-11eb-93ec-b7647f6257b5.png)

**Comment by bluenevus** [comment]
I don't understand this requirement
