### ISSUE TITLE
remove the section that says "incomplete" on this view for task and issues

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#772]
![image](https://user-images.githubusercontent.com/3675043/97934919-1065fb80-1d45-11eb-91ed-8b495fa9762e.png)

**Comment by juan-rivera-2020** [comment]
**Incomplete** status rows (Task & Issues) removed from Facility Summary view.

**Comment by bluenevus** [comment]
still showing up on this view here 
![image](https://user-images.githubusercontent.com/3675043/97947039-0ef2fe00-1d5a-11eb-900f-3193f0f4b5e1.png)
