### ISSUE TITLE
need an option to filter watched tasks and watched issues called "On Watch"

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#780]
here for task and separately issues e.g. Tasks On Watch and Issues On Watch

![image](https://user-images.githubusercontent.com/3675043/97991048-d9c4cb00-1dae-11eb-9613-4310ece1656e.png)

and here checkbox "On Watch"
![image](https://user-images.githubusercontent.com/3675043/97991061-e1846f80-1dae-11eb-9001-37b3595db429.png)

and here checkbox "On Watch"
![image](https://user-images.githubusercontent.com/3675043/97991077-e9441400-1dae-11eb-94ec-22fc20ef9c10.png)

**Comment by LAlexMHllc** [comment]
When a user does not have Read privilege for On Watch View: 
- Tasks On Watch and Issues On Watch should not display on Filter View form
- checkbox "On Watch" should not display on the Tasks and Issues tabs
