### ISSUE TITLE
admin/tasks - Filters form: "Checklist Item Assigned to" should be single-select, not multi-select.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#787]
Screenshot Example

![admin_tasks_filters_checklist_items_should_be_single_select_not_multi-select](https://user-images.githubusercontent.com/11938477/98013888-f110b200-1dc8-11eb-9b88-f553cec994e3.png)

**Comment by bluenevus** [comment]
there are multiple people assigned.  we do need a multiselect but its an OR statement not an AND statement
