### ISSUE TITLE
admin/issues - Filters form: "Checklist Item Assigned to" should be single-select, not multi-select

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#788]
Screenshot Example

![admin_issues_filters_checklist_items_should_be_single_select_not_multi-select](https://user-images.githubusercontent.com/11938477/98014320-772cf880-1dc9-11eb-9a2e-8eb044c07720.png)

**Comment by bluenevus** [comment]
this should be multiselect and it should be an OR statement not an AND statement
