### ISSUE TITLE
Client Panel - Project screen not loading. Not sure if it's due to slow internet connection OR if broken by code.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#796]
Tried loading screen several times in different browsers.
Screenshot Example

![client_panel_project_screen_not_loading](https://user-images.githubusercontent.com/11938477/98034480-0e537980-1de5-11eb-95be-1fb5aa1c1859.png)

**Comment by bluenevus** [comment]
its working.  might be internet
