### ISSUE TITLE
Client Panel - Edit Task and Edit Issue: Include "Delete" next to Save and Cancel

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#804]

**Comment by bluenevus** [comment]
yes

**Comment by LAlexMHllc** [comment]
"Save" and "Cancel" will display for user with Write privilege, and the "Delete" will display for user with Delete privilege.
None of them will display for user with Read privilege only.

How about the color of "Cancel" being orange instead of red (see Issue #781), and the color of "Delete" be red?

Screenshot Example

![save_cancel_delete_buttons](https://user-images.githubusercontent.com/11938477/98137422-f8e75980-1e8f-11eb-9247-355e4809b7b2.png)

**Comment by curtismayer** [comment]
I suggest the Delete button be right aligned with the Save and Cancel remaining left aligned as it currently is now.  Doing this limits pushing the Delete button by mistake.
