### ISSUE TITLE
new tab called sheets

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#809]
![image](https://user-images.githubusercontent.com/3675043/98181726-f60d5880-1ed1-11eb-8e24-aac3aae5ec5b.png)

**Comment by bluenevus** [comment]
we also need these filters and the add button like it is on task and issues

for issues 
![image](https://user-images.githubusercontent.com/3675043/98278021-01aa5f00-1f66-11eb-93d9-ae7cc100fe06.png)

for tasks

![image](https://user-images.githubusercontent.com/3675043/98277994-f8b98d80-1f65-11eb-8fe0-5b355bc35a6c.png)

**Comment by bluenevus** [comment]
be sure to paginate else the page will go on forever.  and you need a search box on the title

**Comment by juan-rivera-2020** [comment]
Sounds good.  Will do.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

Juan Rivera
Developer
t: 855-294-3547
m: 508-596-3665
juan.rivera@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.
