### ISSUE TITLE
slow loading of vue for the first time / slow loading after refresh

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#815]
looks like this article addresses this.  We did implement skeleton loading however, its still 20 seconds before the user is even able to begin working in the system on page load

https://programmer.ink/think/5dc2306720c0a.html

https://www.programmersought.com/article/55584652028/

https://www.creativebloq.com/news/speed-up-performance-with-vuejs

**Comment by bluenevus** [comment]
it appears to be the calculations of the overview page.  We may need to optimize it or may need to cache the calc or both.  We may need to consider a different first page that doesn't do all the math so they can get right to work in task and issues and load the math in the background.  I think we will need to be creative to give the user a better experience on first load because its 20 seconds before they can begin work on the page and we fear clicking the refresh button

**Comment by bluenevus** [comment]
some improvement, we did shave off about 5 seconds but we need to shave off more.  we may have to implement 1037 to see that so we will keep this issue open until we see 1037 or some other strategy like caching or something

**Comment by LAlexMHllc** [comment]
Closing, since Issue #1037 was closed
