### ISSUE TITLE
Edit User Profile - "Title" should be changed to "Position", and remove "Mr." placeholder.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#824]
Screenshot Example

![edit_user_profile_title_placeholder](https://user-images.githubusercontent.com/11938477/98287090-e003a480-1f72-11eb-80e7-4fada2659e8f.png)

**Comment by bluenevus** [comment]
I keep saying its not job title.  Its position and no matter how many times I say it, you keep saying job titile
