### ISSUE TITLE
User without Write privilege can not view admin/users.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#830]
Screenshot Examples from Chrome in dev

![admin_users_error_without_write_privilege_chrome_dev](https://user-images.githubusercontent.com/11938477/98383705-d6357c00-201a-11eb-9ce3-8c445c0221a7.png)

**Comment by bluenevus** [comment]
I'm just not seeing this error.  maybe its happening when you test during the build cycle.

**Comment by LAlexMHllc** [comment]
Screenshot Example in Firefox for prod

![admin_users_error_without_write_privilege_chrome_prod](https://user-images.githubusercontent.com/11938477/98384691-16e1c500-201c-11eb-9185-cc155bc662e0.png)
