### ISSUE TITLE
colors are reversed on the pagination of updates in task and issues

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#840]
seems like blue and underline is indicative of a hyperlink so most people would think the black is the page you are on which isn't a link and the blue is a link to the next page or page number
![image](https://user-images.githubusercontent.com/3675043/98304094-4c8b9d00-1f8d-11eb-8b07-daf004886006.png)

**Comment by juan-rivera-2020** [comment]
This one's ready to close if satisfied with the styling.  Active page number is bold, no underline, with default cursor.  Additional page has pointer cursor and clickable.

**Comment by bluenevus** [comment]
it is still reversed.  the page you're on is blue and the page you will navigate to is black
![image](https://user-images.githubusercontent.com/3675043/99547782-f142ad00-2985-11eb-9045-cdce7daff541.png)
![image](https://user-images.githubusercontent.com/3675043/99547919-19caa700-2986-11eb-8cbc-cb98ac3e8165.png)

**Comment by juan-rivera-2020** [comment]
Looking into it now.
