### ISSUE TITLE
need a filter drop down in the filter handle for overdue issues and tasks

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#841]
![image](https://user-images.githubusercontent.com/3675043/98304459-0420af00-1f8e-11eb-93d6-d23b1621d379.png)

so the option would be "overdue" and "not overdue" or it not applied.  this way they can see those tasks overdue or only tasks not overdue or that filter cleared

**Comment by bluenevus** [comment]
also the choice of things Not Overdue so it filters OUT things that are overdue

**Comment by bluenevus** [comment]
if we can fit overdue in this area, we need it there too 
![image](https://user-images.githubusercontent.com/3675043/99015161-4fa10300-2522-11eb-96cd-b3c5f9c40a91.png)

**Comment by bluenevus** [comment]
this is related to #923

**Comment by microhealthamand** [comment]
Facility manager view > Task
![image](https://user-images.githubusercontent.com/74916983/102395797-9bbfe700-3fa9-11eb-8ebe-60400eeadd17.png)

Facility manager view > Issue
![image](https://user-images.githubusercontent.com/74916983/102395906-bd20d300-3fa9-11eb-94af-3bc26d566c1d.png)

Sheets view > Task
![image](https://user-images.githubusercontent.com/74916983/102395994-d9247480-3fa9-11eb-9a0a-74129d8fa886.png)

Sheets view > Issue
![image](https://user-images.githubusercontent.com/74916983/102396046-e6d9fa00-3fa9-11eb-9fcb-cb55717e5bda.png)

Kanban view > Task
![image](https://user-images.githubusercontent.com/74916983/102396089-f35e5280-3fa9-11eb-8d76-3959ef7097bd.png)

Kanban view > Issue
![image](https://user-images.githubusercontent.com/74916983/102396239-27d20e80-3faa-11eb-9cce-c597b9e6de29.png)

Global filter
![image](https://user-images.githubusercontent.com/74916983/102396239-27d20e80-3faa-11eb-9cce-c597b9e6de29.png)

**Comment by LAlexMHllc** [comment]
See related Issue #1087
