### ISSUE TITLE
save, cancel, delete along issue/task/notes actions & filters should be a persistent menu that stay on the screen at the top while scrolling

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#842]
when this is persistently at the top of the issue form, task form and notes form, the user doesn't have to scroll down to the bottom to perform these actions as it will always be on the screen.  it would also negate the need for the back button as this menu below would be persistent in the view when scrolling up and down

![image](https://user-images.githubusercontent.com/3675043/98309557-c37a6300-1f98-11eb-985c-48c6d207beeb.png)

the same needs to go for this so the user doesn't need to scroll all the way back up to perform these actions for task, notes and issues

![image](https://user-images.githubusercontent.com/3675043/98309577-d12fe880-1f98-11eb-843c-1daee817a4f4.png)

**Comment by juan-rivera-2020** [comment]
I was thinking along the same lines.  I'll make it happen.

**Comment by bluenevus** [comment]
when you see a workaround to a user experience that seems like just a workaround and really it needs to be something different.  just post a comment on what it should be, I'll reply.  most likely, I'm looking for a better user experience and the requirement may too specific to address that telling developers exactly what to do when really we need to tell you what we want to achieve so you can figure out the best way to achieve that goal

**Comment by juan-rivera-2020** [comment]
Got it!  In this case, I'm planning to place the action buttons on the top of the form with a sticky-top.  The sticky-top will ensure that the User can scroll as far down (or up) with the action buttons staying in place to enhance the UX.

**Comment by LAlexMHllc** [comment]
Still needs to be done for Notes

Screenshot Example

![facility_summary_notes_buttons_stationary](https://user-images.githubusercontent.com/11938477/98709452-63950b00-2350-11eb-9b90-977be51e7533.png)
