### ISSUE TITLE
For the issues and task exports, please add column after milestone called Facility and put the facility name

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#843]
For the issues and task exports, please add column after milestone called Facility and put the facility name

**Comment by LAlexMHllc** [comment]
NOTE: See Issue #873 regarding "Milestone" change to "Task Category"

**Comment by bluenevus** [comment]
but we don't need it on the sheets view, just the export

**Comment by juan-rivera-2020** [comment]
This is also complete... Please close.  
![image](https://user-images.githubusercontent.com/72885316/99451442-33b9aa80-28f0-11eb-8788-9dc0b311b21b.png)
