### ISSUE TITLE
Issues need a new field called Task Category...same drop down in tasks

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#864]
Issues need a new field called Task Category...same drop down in tasks

The purpose is that issues are specific to certain milestones and so when the user filters a milestones, only those issues associated with that milestone should display.

Also the overview reports will need to get updated so the issues filter out also when a milestone is applied.

If a task category is applied, the issue task category should automatically be applied.  if an issue task category is applied the task category should automatically be applied as the purpose is to filter issues and tasks associated with that task category

**Comment by LAlexMHllc** [comment]
NOTE: See Issue #873 regarding "Milestone" change to "Task Category"

**Comment by bluenevus** [comment]
I don't see task category here in issues

![image](https://user-images.githubusercontent.com/3675043/101225739-3c381200-3660-11eb-8426-3cb7a0a397bc.png)

like it is under tasks

![image](https://user-images.githubusercontent.com/3675043/101225756-46f2a700-3660-11eb-89a5-f14979394820.png)

I'm looking for that same thing in issues
