### ISSUE TITLE
Project screen - Map view - Facility Summary - Notes forms: Fix position/display for forms; also should not have double scrollbars.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#875]
Screenshot Example of Add Note

![facility_summary_notes_add_position_and_scrollbar](https://user-images.githubusercontent.com/11938477/98562438-1180b680-2278-11eb-851c-8edb796c8a02.png)

Screenshot Example of Edit Note

![facility_summary_notes_edit_position_and_scrollbar](https://user-images.githubusercontent.com/11938477/98562452-147ba700-2278-11eb-9d40-da467f27c36e.png)

**Comment by bluenevus** [comment]
maybe fixed with #711
