### ISSUE TITLE
Facility Summary - Overview: Include "Cancel" button when "Save" is displayed. Make button bar stationary and position on top like the others.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#879]
User edited Project Status and/or Project Completion Date, so the Save button displayed.
Screenshot Example

![facility_summary_overview_include_cancel_along_with_save](https://user-images.githubusercontent.com/11938477/98581095-f53c4400-228e-11eb-92f3-8c3d3b473487.png)

**Comment by bluenevus** [comment]
not sure why we need a cancel button.  nothing will be seen

**Comment by LAlexMHllc** [comment]
1. Should have the "Cancel" along with the "Save" to be consistent.
2. Once the user edits Overview, the Save button will display; even when the user reverts their selection(s), or clicks another tab, then returns to Overview.
3. The Overview values should be clear to the user without having to select another facility or view tab, then returning to this Facility Summary.

Screenshot Example

![facility_summary_overview_edit_save_display_1](https://user-images.githubusercontent.com/11938477/98691334-ed86a900-233b-11eb-86f4-0e5cd2b65759.png)

![facility_summary_overview_edit_save_display_2](https://user-images.githubusercontent.com/11938477/98691299-e3fd4100-233b-11eb-9efb-da97699d8d79.png)

**Comment by LAlexMHllc** [comment]
Make button row stationary and positioned on top like the others.
NOTE: No Delete button

Screenshot Example

![facility_summary_overview_save_cancel_stationary](https://user-images.githubusercontent.com/11938477/98711981-b7552380-2353-11eb-8bef-0cd31190f002.png)

**Comment by bluenevus** [comment]
I really don't want to invest in this.  the date will be automatically calculated based on the last task completion date that we need to put in.  the project status will be automatically calculated based on a ticket I already put in.
