### ISSUE TITLE
filtering by task users or issue users does not work

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#884]
![image](https://user-images.githubusercontent.com/3675043/98709246-22046000-2350-11eb-98b0-15c487388588.png)

![image](https://user-images.githubusercontent.com/3675043/98709331-406a5b80-2350-11eb-921a-f1cf690931d4.png)

results in no change in the task list or issue list.  still lists everyone

**Comment by LAlexMHllc** [comment]
These filter the facilities with assigned users to task or assigned users to issue. Does not function like My Tasks or My Issues.
