### ISSUE TITLE
date range filter for task and issues are not working

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#885]
![image](https://user-images.githubusercontent.com/3675043/98735834-0316c580-2372-11eb-912d-5ae25ba51858.png)

it pulls up everything, no filter applied

then it removes all facilities though there are definitely task and issues in that date range

![image](https://user-images.githubusercontent.com/3675043/98735901-1f1a6700-2372-11eb-9e4c-ad5ea24903a0.png)

**Comment by LAlexMHllc** [comment]
Date Range Filter is for "Project Completion Date".
Should change the Placeholder text so it's not confusing.
