### ISSUE TITLE
Filter View: Should exclude results found in inactive facilities AND active facilities within inactive facility groups

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#899]
Screenshot Example

![filter_view_should_exclude_results_found_inactive_facilties_and_facilities_in_inactive_facility_group](https://user-images.githubusercontent.com/11938477/98846203-bf2cca80-241c-11eb-991f-b768c4a353f7.png)

**Comment by bluenevus** [comment]
we just need to remove inactive from the client view all the way around.  its useless information and confusing at best so lets just REMOVE it.  its an administrative feature

**Comment by bluenevus** [comment]
since you're removing inactive, that means remove active because its simply not needed either because it already shows the active count

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/101935102-88c5a500-3bac-11eb-8ecc-362f1b30ec07.png)
