### ISSUE TITLE
allow users to set their preference on the default landing page when entering a project

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#901]
allow users to set their preference on the default landing page when entering a project from one of these choices below.  

![image](https://user-images.githubusercontent.com/3675043/98867755-20649600-243d-11eb-987e-2a802896e225.png)

it should be where they edit their profile 

![image](https://user-images.githubusercontent.com/3675043/98867814-33776600-243d-11eb-9813-d2d7af4113ab.png)

**Comment by curtismayer** [comment]
If a user selects Sheet they should be provided the option to select Overview, Tasks, Issues, Risks, or Notes. Then they should be able to select a Project Group and Project.

If the user selects Kanban they should be provided the option to select Tasks, Issues, or Risks. Then they should be able to select the Project Group and Project.

**Comment by curtismayer** [comment]
I would create different tabs on the Edit Profile because we will have Profile, Start On, Filter Favorites, and then anything else we think of as time goes on.

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/107435424-216b9900-6afa-11eb-88c9-6a2835303aae.png)

**Comment by LAlexMHllc** [comment]
Options for Sub Navigation should not be selected, nor available options dependent upon Navigation selected.
Screenshot Example

![edit_user_profile_subhead_fix_sub_navigation_options](https://user-images.githubusercontent.com/11938477/108052425-20ff6080-701a-11eb-880b-e8a1c5fe22f8.png)
![edit_user_profile_subhead_fix_sub_navigation_options_2](https://user-images.githubusercontent.com/11938477/108053974-1219ad80-701c-11eb-8b04-4b2ebbe77d63.png)

**Comment by LAlexMHllc** [comment]
No duplicate Project Names
Screenshot Example

![edit_user_profile_no_duplicate_project_names](https://user-images.githubusercontent.com/11938477/108054398-99672100-701c-11eb-951c-fe19737a7bab.png)

**Comment by LAlexMHllc** [comment]
User info belongs under the Profile tab.
The navigation form elements belong under the Start On tab.

**Comment by LAlexMHllc** [comment]
User selected Project Group and the previously selected Project should have cleared since it does not belong in that group.
Screenshot Example

![user_nav_preference_project_not_in_project_group](https://user-images.githubusercontent.com/11938477/108252676-f0f1b380-7126-11eb-9500-3dc90abac774.png)

**Comment by microhealthamand** [comment]
Related https://github.com/MicroHealthLLC/mGis/issues/1786

**Comment by LAlexMHllc** [comment]
Start On still needs to be fixed.

**Comment by LAlexMHllc** [comment]
Start On
Select Sub Navigation did not clear when selected Navigation was deselected. If this is OK, then ignore.
Screenshot Example

![preferences_sub_navigation_did_not_clear_when_navigation_cleared](https://user-images.githubusercontent.com/11938477/108866084-deadc480-75c1-11eb-9b21-33d77fb7599c.png)

**Comment by LAlexMHllc** [comment]
Start On
When Gantt or Team are selected for Navigation, all options for Sub Navigation still display. If this is OK, then ignore.
Screenshot Example

![all_sub_navigation_options_display_for_gantt_and_team_selected_navigation](https://user-images.githubusercontent.com/11938477/108866766-7e6b5280-75c2-11eb-964c-5da50db8fcb4.png)

**Comment by LAlexMHllc** [comment]
NOTE: Will come back and test this again after Issue #1807 is fixed.

**Comment by LAlexMHllc** [comment]
Screenshot Example of Preferences and Start On with Map selected for Navigation

![preferences_start_on_map_task](https://user-images.githubusercontent.com/11938477/108890406-897eac80-75db-11eb-8d30-789a9645e7a4.png)

When Update clicked, the Program Summary displayed on Map view instead of Project Summary of selected project.
Screenshot Example

![preferences_start_on_map_task_result_map_program_summary](https://user-images.githubusercontent.com/11938477/108890504-ac10c580-75db-11eb-93fe-8e1d481fdbae.png)

When user selected pushpin, the Overview tab displayed instead of Tasks tab.
Screenshot Example

![preferences_start_on_map_task_result_project_overview_instead_of_tasks](https://user-images.githubusercontent.com/11938477/108890624-cf3b7500-75db-11eb-8aac-a4aa465fd398.png)

**Comment by LAlexMHllc** [comment]
Selected Gantt for Navigation, then clicked Update. Clicked Gantt tab, chart did not load, just kept Loading...
Screenshot Example

![user_preferences_start_on_Gantt_screen_loading](https://user-images.githubusercontent.com/11938477/108907426-0f0c5780-75f0-11eb-9584-c02177cb6680.png)

**Comment by LAlexMHllc** [comment]
See related Issue #1839

**Comment by LAlexMHllc** [comment]
Select Navigation should only include options that user has Read privilege.
Screenshot Example

![user_profile_select_navigation_options_require_Read_privilege](https://user-images.githubusercontent.com/11938477/109033534-bd69d880-7694-11eb-9a1c-6f6d702cbfc4.png)

**Comment by LAlexMHllc** [comment]
Closing, since Preferences and Start On was included on Edit User Profile, along with several updates.
NOTE: Will input separate issues related to this enhancement.
