### ISSUE TITLE
need a filter for task due date range an issue due date range on the filter handle

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#902]
need a filter for task due date range an issue due date range on the filter handle

**Comment by bluenevus** [comment]
related to#859 and #841

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102128177-7b622200-3e1b-11eb-82cd-759460eb5465.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102142100-dc93f080-3e2f-11eb-9f4e-7b384ed01940.png)

**Comment by LAlexMHllc** [comment]
Did not filter On Watch and Gantt views

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102251690-2681e280-3ed3-11eb-96f9-d7483d064477.png)

Change in placeholder text
![image](https://user-images.githubusercontent.com/74916983/102251766-3dc0d000-3ed3-11eb-966c-54843f9e67bc.png)
