### ISSUE TITLE
Rename Facility to Project throughout the application

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#920]
instead of facility manager, project manager
instead of facility progress, project progress
instead of facility sheets, project sheets
instead of facility groups, project groups
instead of facility summary, project summary

..and so on and so forth.

where it says Project right now, rename that Program
![image](https://user-images.githubusercontent.com/3675043/99130821-6a857d00-25df-11eb-9000-7e4d8d8b2617.png)

**Comment by juan-rivera-2020** [comment]
Changes in Client Panel don't present an issue.  In the Admin Panel, however, there's a tab called Organization under Users which may present some confusion.  Should we stick with Facilities in the Admin Panel, since it's sort of like a "backend" for the Admin anyway?

**Comment by bluenevus** [comment]
the facilities under admin panel has to be organization also.  all needs to be organization

the organization under user can be "Company"

**Comment by juan-rivera-2020** [comment]
Sounds good =)


Juan Rivera
Developer
t: 855-294-3547
m: 508-596-3665
juan.rivera@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by bluenevus** [comment]
other examples here 
![image](https://user-images.githubusercontent.com/3675043/103365245-a0969780-4a8d-11eb-8a41-26cdaa1a3be3.png)

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/105408182-9f740880-5bfc-11eb-9b6c-ea13c8aa2899.png)


![image](https://user-images.githubusercontent.com/74916983/105408234-b155ab80-5bfc-11eb-83b1-a1759b89b8a2.png)

**Comment by LAlexMHllc** [comment]
Closing, since mentioned changes were done.
NOTE: Still need to fix related Issues #1576, #1579 through #1588, etc.
