### ISSUE TITLE
please list the filters applied on the overview screens in facility manager, maps, and sheets

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#922]
![image](https://user-images.githubusercontent.com/3675043/99014401-9c83da00-2520-11eb-9f2e-8679cda918f8.png)

Before tasks and after facility progress

Put a header that says "Data Set Filters" 

Then under it list only the filters apply.

For Example

Milestone: Concept Review
Facility Group: Group A, Group B
Status: On schedule

This way the users know what filtered dataset they are working on

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/102830172-b71a6000-43b6-11eb-8d7f-6f55cb519043.png)

**Comment by microhealthamand** [comment]
Map View
![image](https://user-images.githubusercontent.com/74916983/102921893-26499000-445b-11eb-9222-8d5df993e191.png)

Sheets view
![image](https://user-images.githubusercontent.com/74916983/102922114-7f192880-445b-11eb-9f91-e8fa03795a7c.png)

Facility Manager View
![image](https://user-images.githubusercontent.com/74916983/102922180-9821d980-445b-11eb-8f95-3f139094c466.png)

**Comment by bluenevus** [comment]
coolzies

**Comment by LAlexMHllc** [comment]
Closing issue; see Issue #1259
