### ISSUE TITLE
instead of a blank page that says "View, Add or Edit Tasks, Issues, and Notes here." on facility manager, put some basic metrics

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#925]
instead of a blank page that says "View, Add or Edit Tasks, Issues, and Notes here." on facility manager, put some basic metrics in graphical form like 
![image](https://user-images.githubusercontent.com/3675043/99119623-7d8c5300-25c7-11eb-8ef1-49e4fb8be5ac.png)

based on what is filtered

burndown chart on completed tasks and tasks remaining  https://en.wikipedia.org/wiki/Burn_down_chart https://en.wikipedia.org/wiki/Burn_down_chart#/media/File:SampleBurndownChart.svg this will take the time period of what is filtered (like what would show on the gantt) y axis is number of tasks.  x axis is timeline.  this gives a visual of how quickly we are closing tasks

bar chart on task count based on percentages  y axis is number of tasks.  x axis percentage complete in 25% intervals.  0, 1%-25%, 26%-50%, 51%-75%, 76%=99% , 100% this gives a visual of how many tasks fall into these completion buckets.

Number of Users with Tasks Assigned vs Not assigned
Number of Tasks Complete vs Incomplete
Percentage Task Complete vs Incomplete
Percentage of Task Overdue vs On Schedule

Burndown chart on completed issues and issue remaining  https://en.wikipedia.org/wiki/Burn_down_chart https://en.wikipedia.org/wiki/Burn_down_chart#/media/File:SampleBurndownChart.svg  this will take the time period of what is filtered (like what would show on the gantt) y axis is number of tasks.  x axis is timeline. this gives a visual of how quickly we are closing issues

bar chart on issue count based on percentages  y axis is number of issues.  x axis percentage complete in 25% intervals.  0, 1%-25%, 26%-50%, 51%-75%, 76%=99% , 100% this gives a visual of how many tasks fall into these completion buckets.

Number of Users with Issues Assigned vs Not assigned
Number of Issues Complete vs Incomplete
Percentage Issue Complete vs Incomplete
Percentage of Issue Overdue vs On Schedule

**Comment by LAlexMHllc** [comment]
Closing due to Issue #1592
