### ISSUE TITLE
On Watch View - When user has Read only privilege, they can not close the Task modal or Issue modal. User has to reload the screen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#926]

**Comment by bluenevus** [comment]
I really don't understand what this means. Can you explain it and describe the steps.

**Comment by LAlexMHllc** [comment]
EXAMPLE
User with Read only privilege clicks a watched task on the On Watch View screen. The Task modal displays. User can not close the modal.

Screenshot Example

![on_watch_user_with_read_only_privilege_task_and_issue_modal](https://user-images.githubusercontent.com/11938477/99126942-23928a00-25d5-11eb-93a1-b96a9cff22f9.png)
