### ISSUE TITLE
Project screen - Filter View: Should update filter query for "Search by Facility Name" when "Select Facility Group" is selected. Otherwise, when selected facility does not belong to the selected facility group, the result is always 0 Facilities.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#929]
User selected a facility group and 47 facilities were found.
User then selected a facility that does not belong to the selected facility group, and 0 facilities were found.

Screenshot Example

![filter_view_facility_group_and_facility_name](https://user-images.githubusercontent.com/11938477/99133199-f51daa80-25e6-11eb-8de0-5d3a3ccfeaab.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![filter_view_facility_group_and_facility_name_2](https://user-images.githubusercontent.com/11938477/99132891-eb477780-25e5-11eb-8658-a88c2897b1bb.png)

**Comment by bluenevus** [comment]
I don't understand

**Comment by bluenevus** [comment]
you need to walk through the steps to get to the issue and describe what the expected results were hen explain what it actually did instead of the expected reults

**Comment by bluenevus** [comment]
we are not changing it to Or statement for one use case

**Comment by LAlexMHllc** [comment]
Depending on how you want this to function:

OPTION 1: "Search by Facility Name" options should be dependent upon selected "Search by Facility Group".
Once a Facility Group is selected, only facilities within that facility group will display as options for Search by Facility Name.

OR

OPTION 2: The filter query should be "Search by Facility Group" OR "Search by Facility Name" with results including all facilities within selected group(s) + any facilities selected that are not in that group.

**Comment by bluenevus** [comment]
go back and explain the problem in a new ticket.  explain the steps to get there.  say what the expected result was and the actual result.  let the developers come up with the solution.

WE ARE NOT DOING AN OR STATEMENT  you will mess up everything else.  stop telling developers how to fix a problem.  describe the problem and let developers do their job and coming up with the solution
