### ISSUE TITLE
Sheets View - User without Write privilege is not able to close the Task form and Note form.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#940]
Screenshot Example

![sheets_view_user_without_write_privilege_unable_close_forms](https://user-images.githubusercontent.com/11938477/99306544-5467fe80-2823-11eb-8b76-65474e8049be.png)

**Comment by bluenevus** [comment]
should be able to close with read only priv and NOT require write

**Comment by juan-rivera-2020** [comment]
I just noticed this in the Facility Manager view as well.  Looking into the issue now.  
![image](https://user-images.githubusercontent.com/72885316/99402150-07ce0300-28b7-11eb-9b72-d8d9c865ebd7.png)
