### ISSUE TITLE
provide the ability to change Project for which a task, issue, notes and in the future risk was entered

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#947]
right now, people make the mistake of sometimes entering a task, issue, or note on the wrong facility.  the only way to correct that is to delete it and recreate it in the other facility.  Can we have a "change facility" function that will allow them to change task, issue, risk to a different facility?

**Comment by microhealthamand** [comment]
![image](https://user-images.githubusercontent.com/74916983/106332442-d5486b00-6254-11eb-8f2a-4ff9dde8b27f.png)

**Comment by bluenevus** [comment]
well since Facility has been renamed...we need to call it Project

**Comment by bluenevus** [comment]
probably should be more like a header on top of the form so its Project: (drop down list) so its noticeable.  serves 2 purposes.  first so the user knows what active project they are working on in the form, secondly to change this task, issue or risk to another project.

**Comment by LAlexMHllc** [comment]
Change "Facility" to "Project" on forms, and make drop-down a search/select (like ADVANCED FILTERS)
Screenshot Example

![action_forms_change_facility_to_project_make_search_select](https://user-images.githubusercontent.com/11938477/106636335-d4168700-654f-11eb-937a-99eb07b21f15.png)

**Comment by LAlexMHllc** [comment]
Closing, since Facility was changed to Project, and "Move" will replace Project select.
