### ISSUE TITLE
For on watch, remove the rest of the reports like watched task stats and watched issue stats and replace with the actual list of task and issues

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#955]
Remove all the reports below this section of on watch

![image](https://user-images.githubusercontent.com/3675043/99445518-a2e0d000-28eb-11eb-8445-f4d4bf6a040b.png)

then replace those reports with task, then issues side by side filling up about 800px vertical so they don't have to scroll much within the window for each.  Something like so

![image](https://user-images.githubusercontent.com/3675043/99445908-37e3c900-28ec-11eb-8baa-a74ba91fa5f8.png)

also notice in the actual on watch, the watched task and issue provide the facility name and facility group which we will need like so 

![image](https://user-images.githubusercontent.com/3675043/99445961-49c56c00-28ec-11eb-988c-29a1bbba711a.png)

This will give the users the ability manage just on watch tasks easily which is used to keep track of "hot items" that are at multiple facilities

**Comment by bluenevus** [comment]
or maybe use the sheets type view, put 400px of tasks above the issues and 400px of issues below the tasks so you have more horizontal space to look at the core elements.   Its hard to say which way would be more functional or aesthetically pleasing.  both will result in scroll bars within the page scroll bar

**Comment by LAlexMHllc** [comment]
Closing since On Watch view is deprecated
