### ISSUE TITLE
Project - Sheets view: When a Facility Group link is clicked open, the Facility Group Summary should display like it does on the Facility Manager view.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#961]
Screenshot Example

![sheets_view_facility_group_sidebar_clicked_open_display_facility_group_summary](https://user-images.githubusercontent.com/11938477/99588109-19e39a80-29b8-11eb-947f-c111a15e7cb1.png)

**Comment by bluenevus** [comment]
don't understand.  in prod it seems to work fine

**Comment by LAlexMHllc** [comment]
In prod it does not work fine. But leaving closed, since this is now part of Issue #975,
