### ISSUE TITLE
new filter in the filter date for last update in issues and task date range

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#964]
![image](https://user-images.githubusercontent.com/3675043/99605715-3b537f00-29d6-11eb-8ae7-c8157aff8849.png)

I would like to be able to select a date range based on this update note date below

![image](https://user-images.githubusercontent.com/3675043/99605753-53c39980-29d6-11eb-90d9-f467812636bc.png)

**Comment by LAlexMHllc** [comment]
Facility not found for filter when: start date = last date = today date OR last date = today date
EXAMPLE
User added Update Note today.
Screenshot Example

![last_update_today_date](https://user-images.githubusercontent.com/11938477/101921236-c4f00a00-3b9a-11eb-961d-9ddde593300a.png)

User filtered with start date = last date = today date 
THEN last date = today date
Screenshot Example

![last_update_filter_did_not_found_with_today_as_last_date](https://user-images.githubusercontent.com/11938477/101922236-d685e180-3b9b-11eb-9810-d2a18e77025a.png)

User filtered with start date = today date and last date = tomorrow date
Screenshot Example

![last_update_filter_found_with_today_as_first_date_tomorrow_as_last_date](https://user-images.githubusercontent.com/11938477/101922350-f917fa80-3b9b-11eb-87df-d498c6a1eb9f.png)

**Comment by LAlexMHllc** [comment]
OPINION: Change text to make it clear that this filters notes under Updates, not Notes.

**Comment by bluenevus** [comment]
seems to work
