### ISSUE TITLE
Facility Manager View and Sheets View: Default left sidebar and default middle panel for Summary should be consistent.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#975]
When all facility group tabs are closed on the left sidebar, the Project Summary should display in the middle panel.
When a facility group tab is open on the left sidebar, that Facility Group Summary should display in the middle panel.

Opinion: The default Facility Manager view and default Sheets view should have all facility group tabs closed on the left sidebar, so that the Project Summary displays (just as it does for Map view). User should get to select which Facility Group Summary they want displayed, instead of default facility group summary that is open by default.

**Comment by bluenevus** [comment]
I don't understand this requirement

**Comment by LAlexMHllc** [comment]
Screenshot of default Facility Manager view

![facility_manager_view_default](https://user-images.githubusercontent.com/11938477/99852153-68c33880-2b4e-11eb-8636-aaefc0d5cc3b.png)

Screenshot of default Sheets view

![sheets_view_default](https://user-images.githubusercontent.com/11938477/99852175-724ca080-2b4e-11eb-8212-a40efe7aaa32.png)

Screenshot of default Map view

![map_view_default](https://user-images.githubusercontent.com/11938477/99852189-7bd60880-2b4e-11eb-95a1-fdcb0c5e366b.png)

**Comment by bluenevus** [comment]
probably should be more like outlook web where it simply remembers your last state and that is how it loads
