### ISSUE TITLE
Project screen - Sheets view: Fix length of Task form and Issue form

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#977]
When a task listing is clicked or an issue listing is clicked, the task/issue modal length is too short to display the form contents.

Screenshot Example

![sheets_view_edit_task_edit_issue_fix_modal_length](https://user-images.githubusercontent.com/11938477/99728434-6ea21680-2a87-11eb-9582-88bcd058dd0c.png)

**Comment by juan-rivera-2020** [comment]
On the dev site (http://192.168.0.58/) the modal sizes currently take up 80% of the screen.  A similar issue was reported to the IT desk yesterday, hence the modification in modal size.  Please let me know if this is still an issue.  
![image](https://user-images.githubusercontent.com/72885316/99752738-e76a9800-2ab2-11eb-8f5d-a54b79ae6453.png)
