### ISSUE TITLE
Project screen - Filter View: Should rearrange selectors

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#992]
Screenshot Example

![filter_view_rearrange_selectors](https://user-images.githubusercontent.com/11938477/99983416-d56e4b00-2d79-11eb-86c8-20a5e8e0c378.png)

**Comment by bluenevus** [comment]
here is the deal...right now I don't want more functionality here.  I need to combine it and fix essential usability

my actions should be one check box for issue, notes tasks.  on watch should be one check box for issues, tasks.  We have missing filters.  Stages should be one dropdown for stage that applies to issues and task not separately.
