### ISSUE TITLE
Project screen - Sheets view: Issues tab: Missing "Stage" column

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#994]
Screenshot Example

![sheets_view_issues_table_missing_stage_column](https://user-images.githubusercontent.com/11938477/99985014-c6889800-2d7b-11eb-82c9-5f842ac7e0d9.png)

**Comment by bluenevus** [comment]
not sure if there is enough space.  we might have to reduce the font to 10

**Comment by bluenevus** [comment]
there is a ticket that adds this but not as a column

**Comment by JuanCodeAtATime** [comment]
Would you like the table to have horizontal scroll?  We would be able to add more columns without column size restrictions.

**Comment by bluenevus** [comment]
no but remember, I have a ticket for the arrows going across the top to pseudo kanban.  that was the purpose to fulfill this also so we wouldn't need to  have a table that is simply too large.  somethings, people will need to open to see because we can't fit it all
