### ISSUE TITLE
Kanban view: Facility Group tabs on the left sidebar should be closed by default.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#995]
See related Issue #975 
Screenshot Example

![kanban_left_sidebar_facility_groups_closed_default](https://user-images.githubusercontent.com/11938477/99988167-4f550300-2d7f-11eb-85cd-7c9d7dc32dde.png)

**Comment by bluenevus** [comment]
probably should be more like outlook web where it simply remembers your last state and that is how it loads
