### ISSUE TITLE
Search by user should be inclusive of all things assigned to the user for checklists, tasks, issues and notes

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#999]
there shouldn't be a separate task users and issues users because users just want to see what is assigned to an individual inclusive of all things tasks, checklists and notes they did

![image](https://user-images.githubusercontent.com/3675043/100029215-c9f14300-2dbe-11eb-8ac0-5cdae7285da0.png)

**Comment by LAlexMHllc** [comment]
Closing this issue without Notes, because notes are not assigned.
